/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.22).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.L2Meas;
import io.swagger.model.PlmnInfo;
import io.swagger.model.ProblemDetails;
import io.swagger.model.RabInfo;
import io.swagger.model.S1BearerInfo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-12-17T10:14:37.794Z[Etc/UTC]")
@Api(value = "queries", description = "the queries API")
public interface QueriesApi {

    @ApiOperation(value = "Retrieve information on layer 2 measurements", nickname = "layer2MeasInfoGET", notes = "Queries information about the layer 2 measurements.", response = L2Meas.class, tags={ "rni", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response to layer2 measurements info request", response = L2Meas.class),
        @ApiResponse(code = 400, message = "Bad Request : used to indicate that incorrect parameters were passed to the request.", response = ProblemDetails.class),
        @ApiResponse(code = 401, message = "Unauthorized :  used when the client did not submit credentials.", response = ProblemDetails.class),
        @ApiResponse(code = 403, message = "Forbidden :  operation is not allowed given the current status of the resource.", response = ProblemDetails.class),
        @ApiResponse(code = 404, message = "Not Found :  used when a client provided a URI that cannot be mapped to a valid resource URI.", response = ProblemDetails.class),
        @ApiResponse(code = 406, message = "Not Acceptable : used to indicate that the server cannot provide the any of the content formats supported by the client.", response = ProblemDetails.class),
        @ApiResponse(code = 414, message = "URI Too Long : used to indicate that the server is refusing to process the request because the request URI is longer than the server is willing or able to process.", response = ProblemDetails.class),
        @ApiResponse(code = 429, message = "Too Many Requests : used when a rate limiter has triggered.", response = ProblemDetails.class) })
    @RequestMapping(value = "/queries/layer2_meas",
        produces = { "application/json", "application/problem+json" }, 
        method = RequestMethod.GET)
    ResponseEntity<L2Meas> layer2MeasInfoGET(@ApiParam(value = "Application instance identifier") @Valid @RequestParam(value = "app_ins_id", required = false) String appInsId
,@ApiParam(value = "Comma separated list of E-UTRAN Cell Identities") @Valid @RequestParam(value = "cell_id", required = false) List<String> cellId
,@ApiParam(value = "Comma separated list of IE IPv4 addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "ue_ipv4_address", required = false) List<String> ueIpv4Address
,@ApiParam(value = "Comma separated list of IE IPv6 addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "ue_ipv6_address", required = false) List<String> ueIpv6Address
,@ApiParam(value = "Comma separated list of IE NATed IP addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "nated_ip_address", required = false) List<String> natedIpAddress
,@ApiParam(value = "Comma separated list of GTP TEID addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "gtp_teid", required = false) List<String> gtpTeid
,@ApiParam(value = "PRB usage for downlink GBR traffic in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_gbr_prb_usage_cell", required = false) Integer dlGbrPrbUsageCell
,@ApiParam(value = "PRB usage for uplink GBR traffic in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_gbr_prb_usage_cell", required = false) Integer ulGbrPrbUsageCell
,@ApiParam(value = "PRB usage for downlink non-GBR traffic in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_nongbr_prb_usage_cell", required = false) Integer dlNongbrPrbUsageCell
,@ApiParam(value = "PRB usage for uplink non-GBR traffic in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_nongbr_prb_usage_cell", required = false) Integer ulNongbrPrbUsageCell
,@ApiParam(value = "PRB usage for total downlink traffic in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_total_prb_usage_cell", required = false) Integer dlTotalPrbUsageCell
,@ApiParam(value = "PRB usage for total uplink traffic in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_total_prb_usage_cell", required = false) Integer ulTotalPrbUsageCell
,@ApiParam(value = "Received dedicated preambles in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "received_dedicated_preambles_cell", required = false) Integer receivedDedicatedPreamblesCell
,@ApiParam(value = "Received randomly selected preambles in the low range in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "received_randomly_selected_preambles_low_range_cell", required = false) Integer receivedRandomlySelectedPreamblesLowRangeCell
,@ApiParam(value = "Received rendomly selected preambles in the high range in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "received_randomly_selected_preambles_high_range_cell", required = false) Integer receivedRandomlySelectedPreamblesHighRangeCell
,@ApiParam(value = "Number of active UEs with downlink GBR traffic as defined in ETSI TS 136 314") @Valid @RequestParam(value = "number_of_active_ue_dl_gbr_cell", required = false) Integer numberOfActiveUeDlGbrCell
,@ApiParam(value = "Number of active UEs with uplink GBR traffic as defined in ETSI TS 136 314") @Valid @RequestParam(value = "number_of_active_ue_ul_gbr_cell", required = false) Integer numberOfActiveUeUlGbrCell
,@ApiParam(value = "Number of active UEs with downlink non-GBR traffic as defined in ETSI TS 136 314") @Valid @RequestParam(value = "number_of_active_ue_dl_nongbr_cell", required = false) Integer numberOfActiveUeDlNongbrCell
,@ApiParam(value = "Number of active UEs with uplink non-GBR traffic as defined in ETSI TS 136 314") @Valid @RequestParam(value = "number_of_active_ue_ul_nongbr_cell", required = false) Integer numberOfActiveUeUlNongbrCell
,@ApiParam(value = "Packet discard rate for downlink GBR traffic in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_gbr_pdr_cell", required = false) Integer dlGbrPdrCell
,@ApiParam(value = "Packet discard rate for uplink GBR traffic in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_gbr_pdr_cell", required = false) Integer ulGbrPdrCell
,@ApiParam(value = "Packet discard rate for downlink non-GBR traffic in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_nongbr_pdr_cell", required = false) Integer dlNongbrPdrCell
,@ApiParam(value = "Packet discard rate for uplink non-GBR traffic in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_nongbr_pdr_cell", required = false) Integer ulNongbrPdrCell
,@ApiParam(value = "Packet delay of downlink GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_gbr_delay_ue", required = false) Integer dlGbrDelayUe
,@ApiParam(value = "Packet delay of uplink GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_gbr_delay_ue", required = false) Integer ulGbrDelayUe
,@ApiParam(value = "Packet delay of downlink non-GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_nongbr_delay_ue", required = false) Integer dlNongbrDelayUe
,@ApiParam(value = "Packet delay of uplink non-GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_nongbr_delay_ue", required = false) Integer ulNongbrDelayUe
,@ApiParam(value = "Packet discard rate of downlink GBR traffic of a UE in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_gbr_pdr_ue", required = false) Integer dlGbrPdrUe
,@ApiParam(value = "Packet discard rate of uplink GBR traffic of a UE in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_gbr_pdr_ue", required = false) Integer ulGbrPdrUe
,@ApiParam(value = "Packet discard rate of downlink non-GBR traffic of a UE in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_nongbr_pdr_ue", required = false) Integer dlNongbrPdrUe
,@ApiParam(value = "Packet discard rate of uplink non-GBR traffic of a UE in percentage as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_nongbr_pdr_ue", required = false) Integer ulNongbrPdrUe
,@ApiParam(value = "Scheduled throughput of downlink GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_gbr_throughput_ue", required = false) Integer dlGbrThroughputUe
,@ApiParam(value = "Scheduled throughput of uplink GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_gbr_throughput_ue", required = false) Integer ulGbrThroughputUe
,@ApiParam(value = "Scheduled throughput of downlink non-GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_nongbr_throughput_ue", required = false) Integer dlNongbrThroughputUe
,@ApiParam(value = "Scheduled throughput of uplink non-GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_nongbr_throughput_ue", required = false) Integer ulNongbrThroughputUe
,@ApiParam(value = "Data volume of downlink GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_gbr_data_volume_ue", required = false) Integer dlGbrDataVolumeUe
,@ApiParam(value = "Data volume of uplink GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_gbr_data_volume_ue", required = false) Integer ulGbrDataVolumeUe
,@ApiParam(value = "Data volume of downlink non-GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "dl_nongbr_data_volume_ue", required = false) Integer dlNongbrDataVolumeUe
,@ApiParam(value = "Data volume of uplink non-GBR traffic of a UE as defined in ETSI TS 136 314") @Valid @RequestParam(value = "ul_nongbr_data_volume_ue", required = false) Integer ulNongbrDataVolumeUe
);


    @ApiOperation(value = "Retrieve information on the underlying Mobile Network that the MEC application is associated to", nickname = "plmnInfoGET", notes = "Queries information about the Mobile Network", response = PlmnInfo.class, responseContainer = "List", tags={ "rni", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response to plmn_info request", response = PlmnInfo.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad Request : used to indicate that incorrect parameters were passed to the request.", response = ProblemDetails.class),
        @ApiResponse(code = 401, message = "Unauthorized :  used when the client did not submit credentials.", response = ProblemDetails.class),
        @ApiResponse(code = 403, message = "Forbidden :  operation is not allowed given the current status of the resource.", response = ProblemDetails.class),
        @ApiResponse(code = 404, message = "Not Found :  used when a client provided a URI that cannot be mapped to a valid resource URI.", response = ProblemDetails.class),
        @ApiResponse(code = 406, message = "Not Acceptable : used to indicate that the server cannot provide the any of the content formats supported by the client.", response = ProblemDetails.class),
        @ApiResponse(code = 429, message = "Too Many Requests : used when a rate limiter has triggered.", response = ProblemDetails.class) })
    @RequestMapping(value = "/queries/plmn_info",
        produces = { "application/json", "application/problem+json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<PlmnInfo>> plmnInfoGET(@NotNull @ApiParam(value = "Comma separated list of Application instance identifiers", required = true) @Valid @RequestParam(value = "app_ins_id", required = true) List<String> appInsId
);


    @ApiOperation(value = "Retrieve information on Radio Access Bearers", nickname = "rabInfoGET", notes = "Queries information about the Radio Access Bearers", response = RabInfo.class, tags={ "rni", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response to rab_info request", response = RabInfo.class),
        @ApiResponse(code = 400, message = "Bad Request : used to indicate that incorrect parameters were passed to the request.", response = ProblemDetails.class),
        @ApiResponse(code = 401, message = "Unauthorized :  used when the client did not submit credentials.", response = ProblemDetails.class),
        @ApiResponse(code = 403, message = "Forbidden :  operation is not allowed given the current status of the resource.", response = ProblemDetails.class),
        @ApiResponse(code = 404, message = "Not Found :  used when a client provided a URI that cannot be mapped to a valid resource URI.", response = ProblemDetails.class),
        @ApiResponse(code = 406, message = "Not Acceptable : used to indicate that the server cannot provide the any of the content formats supported by the client.", response = ProblemDetails.class),
        @ApiResponse(code = 429, message = "Too Many Requests : used when a rate limiter has triggered.", response = ProblemDetails.class) })
    @RequestMapping(value = "/queries/rab_info",
        produces = { "application/json", "application/problem+json" }, 
        method = RequestMethod.GET)
    ResponseEntity<RabInfo> rabInfoGET(@ApiParam(value = "Application instance identifier") @Valid @RequestParam(value = "app_ins_id", required = false) String appInsId
,@ApiParam(value = "Comma separated list of E-UTRAN Cell Identities") @Valid @RequestParam(value = "cell_id", required = false) List<String> cellId
,@ApiParam(value = "Comma separated list of IE IPv4 addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "ue_ipv4_address", required = false) List<String> ueIpv4Address
,@ApiParam(value = "Comma separated list of IE IPv6 addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "ue_ipv6_address", required = false) List<String> ueIpv6Address
,@ApiParam(value = "Comma separated list of IE NATed IP addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "nated_ip_address", required = false) List<String> natedIpAddress
,@ApiParam(value = "Comma separated list of GTP TEID addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "gtp_teid", required = false) List<String> gtpTeid
,@ApiParam(value = "E-RAB identifier") @Valid @RequestParam(value = "erab_id", required = false) Integer erabId
,@ApiParam(value = "QoS Class Identifier as defined in ETSI TS 123 401") @Valid @RequestParam(value = "qci", required = false) Integer qci
,@ApiParam(value = "Maximum downlink E-RAB Bit Rate as defined in ETSI TS 123 401") @Valid @RequestParam(value = "erab_mbr_dl", required = false) Integer erabMbrDl
,@ApiParam(value = "Maximum uplink E-RAB Bit Rate as defined in ETSI TS 123 401") @Valid @RequestParam(value = "erab_mbr_ul", required = false) Integer erabMbrUl
,@ApiParam(value = "Guaranteed downlink E-RAB Bit Rate as defined in ETSI TS 123 401") @Valid @RequestParam(value = "erab_gbr_dl", required = false) Integer erabGbrDl
,@ApiParam(value = "Guaranteed uplink E-RAB Bit Rate as defined in ETSI TS 123 401") @Valid @RequestParam(value = "erab_gbr_ul", required = false) Integer erabGbrUl
);


    @ApiOperation(value = "Retrieve S1-U bearer information related to specific UE(s)", nickname = "s1BearerInfoGET", notes = "Queries information about the S1 bearer(s)", response = S1BearerInfo.class, tags={ "rni", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful response to s1_bearer_info request", response = S1BearerInfo.class),
        @ApiResponse(code = 400, message = "Bad Request : used to indicate that incorrect parameters were passed to the request.", response = ProblemDetails.class),
        @ApiResponse(code = 401, message = "Unauthorized :  used when the client did not submit credentials.", response = ProblemDetails.class),
        @ApiResponse(code = 403, message = "Forbidden :  operation is not allowed given the current status of the resource.", response = ProblemDetails.class),
        @ApiResponse(code = 404, message = "Not Found :  used when a client provided a URI that cannot be mapped to a valid resource URI.", response = ProblemDetails.class),
        @ApiResponse(code = 406, message = "Not Acceptable : used to indicate that the server cannot provide the any of the content formats supported by the client.", response = ProblemDetails.class),
        @ApiResponse(code = 429, message = "Too Many Requests : used when a rate limiter has triggered.", response = ProblemDetails.class) })
    @RequestMapping(value = "/queries/s1_bearer_info",
        produces = { "application/json", "application/problem+json" }, 
        method = RequestMethod.GET)
    ResponseEntity<S1BearerInfo> s1BearerInfoGET(@ApiParam(value = "Comma separated list of temporary identifiers allocated for the specific UE as defined in   ETSI TS 136 413") @Valid @RequestParam(value = "temp_ue_id", required = false) List<String> tempUeId
,@ApiParam(value = "Comma separated list of IE IPv4 addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "ue_ipv4_address", required = false) List<String> ueIpv4Address
,@ApiParam(value = "Comma separated list of IE IPv6 addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "ue_ipv6_address", required = false) List<String> ueIpv6Address
,@ApiParam(value = "Comma separated list of IE NATed IP addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "nated_ip_address", required = false) List<String> natedIpAddress
,@ApiParam(value = "Comma separated list of GTP TEID addresses as defined for the type for AssociateId") @Valid @RequestParam(value = "gtp_teid", required = false) List<String> gtpTeid
,@ApiParam(value = "Comma separated list of E-UTRAN Cell Identities") @Valid @RequestParam(value = "cell_id", required = false) List<String> cellId
,@ApiParam(value = "Comma separated list of E-RAB identifiers") @Valid @RequestParam(value = "erab_id", required = false) List<Integer> erabId
);

}

