/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * CaReconfNotificationCarrierAggregationMeasInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class CaReconfNotificationCarrierAggregationMeasInfo {
  @SerializedName("cellIdNei")
  private String cellIdNei = null;

  @SerializedName("cellIdSrv")
  private String cellIdSrv = null;

  @SerializedName("rsrpNei")
  private Integer rsrpNei = null;

  @SerializedName("rsrpSrv")
  private Integer rsrpSrv = null;

  @SerializedName("rsrqNei")
  private Integer rsrqNei = null;

  @SerializedName("rsrqSrv")
  private Integer rsrqSrv = null;

  public CaReconfNotificationCarrierAggregationMeasInfo cellIdNei(String cellIdNei) {
    this.cellIdNei = cellIdNei;
    return this;
  }

   /**
   * Get cellIdNei
   * @return cellIdNei
  **/
  @Schema(description = "")
  public String getCellIdNei() {
    return cellIdNei;
  }

  public void setCellIdNei(String cellIdNei) {
    this.cellIdNei = cellIdNei;
  }

  public CaReconfNotificationCarrierAggregationMeasInfo cellIdSrv(String cellIdSrv) {
    this.cellIdSrv = cellIdSrv;
    return this;
  }

   /**
   * Get cellIdSrv
   * @return cellIdSrv
  **/
  @Schema(description = "")
  public String getCellIdSrv() {
    return cellIdSrv;
  }

  public void setCellIdSrv(String cellIdSrv) {
    this.cellIdSrv = cellIdSrv;
  }

  public CaReconfNotificationCarrierAggregationMeasInfo rsrpNei(Integer rsrpNei) {
    this.rsrpNei = rsrpNei;
    return this;
  }

   /**
   * Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].
   * @return rsrpNei
  **/
  @Schema(description = "Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].")
  public Integer getRsrpNei() {
    return rsrpNei;
  }

  public void setRsrpNei(Integer rsrpNei) {
    this.rsrpNei = rsrpNei;
  }

  public CaReconfNotificationCarrierAggregationMeasInfo rsrpSrv(Integer rsrpSrv) {
    this.rsrpSrv = rsrpSrv;
    return this;
  }

   /**
   * Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].
   * @return rsrpSrv
  **/
  @Schema(description = "Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].")
  public Integer getRsrpSrv() {
    return rsrpSrv;
  }

  public void setRsrpSrv(Integer rsrpSrv) {
    this.rsrpSrv = rsrpSrv;
  }

  public CaReconfNotificationCarrierAggregationMeasInfo rsrqNei(Integer rsrqNei) {
    this.rsrqNei = rsrqNei;
    return this;
  }

   /**
   * Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].
   * @return rsrqNei
  **/
  @Schema(description = "Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].")
  public Integer getRsrqNei() {
    return rsrqNei;
  }

  public void setRsrqNei(Integer rsrqNei) {
    this.rsrqNei = rsrqNei;
  }

  public CaReconfNotificationCarrierAggregationMeasInfo rsrqSrv(Integer rsrqSrv) {
    this.rsrqSrv = rsrqSrv;
    return this;
  }

   /**
   * Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].
   * @return rsrqSrv
  **/
  @Schema(description = "Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].")
  public Integer getRsrqSrv() {
    return rsrqSrv;
  }

  public void setRsrqSrv(Integer rsrqSrv) {
    this.rsrqSrv = rsrqSrv;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaReconfNotificationCarrierAggregationMeasInfo caReconfNotificationCarrierAggregationMeasInfo = (CaReconfNotificationCarrierAggregationMeasInfo) o;
    return Objects.equals(this.cellIdNei, caReconfNotificationCarrierAggregationMeasInfo.cellIdNei) &&
        Objects.equals(this.cellIdSrv, caReconfNotificationCarrierAggregationMeasInfo.cellIdSrv) &&
        Objects.equals(this.rsrpNei, caReconfNotificationCarrierAggregationMeasInfo.rsrpNei) &&
        Objects.equals(this.rsrpSrv, caReconfNotificationCarrierAggregationMeasInfo.rsrpSrv) &&
        Objects.equals(this.rsrqNei, caReconfNotificationCarrierAggregationMeasInfo.rsrqNei) &&
        Objects.equals(this.rsrqSrv, caReconfNotificationCarrierAggregationMeasInfo.rsrqSrv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cellIdNei, cellIdSrv, rsrpNei, rsrpSrv, rsrqNei, rsrqSrv);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaReconfNotificationCarrierAggregationMeasInfo {\n");
    
    sb.append("    cellIdNei: ").append(toIndentedString(cellIdNei)).append("\n");
    sb.append("    cellIdSrv: ").append(toIndentedString(cellIdSrv)).append("\n");
    sb.append("    rsrpNei: ").append(toIndentedString(rsrpNei)).append("\n");
    sb.append("    rsrpSrv: ").append(toIndentedString(rsrpSrv)).append("\n");
    sb.append("    rsrqNei: ").append(toIndentedString(rsrqNei)).append("\n");
    sb.append("    rsrqSrv: ").append(toIndentedString(rsrqSrv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
