/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * The temporary identifier allocated for the specific UE as defined below.
 */
@Schema(description = "The temporary identifier allocated for the specific UE as defined below.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class CellChangeNotificationTempUeId {
  @SerializedName("mmec")
  private String mmec = null;

  @SerializedName("mtmsi")
  private String mtmsi = null;

  public CellChangeNotificationTempUeId mmec(String mmec) {
    this.mmec = mmec;
    return this;
  }

   /**
   * MMEC as defined in ETSI TS 136 413 [i.3].
   * @return mmec
  **/
  @Schema(required = true, description = "MMEC as defined in ETSI TS 136 413 [i.3].")
  public String getMmec() {
    return mmec;
  }

  public void setMmec(String mmec) {
    this.mmec = mmec;
  }

  public CellChangeNotificationTempUeId mtmsi(String mtmsi) {
    this.mtmsi = mtmsi;
    return this;
  }

   /**
   * M-TMSI as defined in ETSI TS 136 413 [i.3].
   * @return mtmsi
  **/
  @Schema(required = true, description = "M-TMSI as defined in ETSI TS 136 413 [i.3].")
  public String getMtmsi() {
    return mtmsi;
  }

  public void setMtmsi(String mtmsi) {
    this.mtmsi = mtmsi;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CellChangeNotificationTempUeId cellChangeNotificationTempUeId = (CellChangeNotificationTempUeId) o;
    return Objects.equals(this.mmec, cellChangeNotificationTempUeId.mmec) &&
        Objects.equals(this.mtmsi, cellChangeNotificationTempUeId.mtmsi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mmec, mtmsi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CellChangeNotificationTempUeId {\n");
    
    sb.append("    mmec: ").append(toIndentedString(mmec)).append("\n");
    sb.append("    mtmsi: ").append(toIndentedString(mtmsi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
