/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * List of filtering criteria for the subscription. Any filtering criteria from below, which is included in the request, shall also be included in the response.
 */
@Schema(description = "List of filtering criteria for the subscription. Any filtering criteria from below, which is included in the request, shall also be included in the response.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class CellChangeSubscriptionFilterCriteriaAssocHo {
  @SerializedName("appInstanceId")
  private String appInstanceId = null;

  @SerializedName("associateId")
  private List<AssociateId> associateId = null;

  @SerializedName("ecgi")
  private List<Ecgi> ecgi = null;

  @SerializedName("hoStatus")
  private List<Integer> hoStatus = null;

  public CellChangeSubscriptionFilterCriteriaAssocHo appInstanceId(String appInstanceId) {
    this.appInstanceId = appInstanceId;
    return this;
  }

   /**
   * Unique identifier for the MEC application instance.
   * @return appInstanceId
  **/
  @Schema(description = "Unique identifier for the MEC application instance.")
  public String getAppInstanceId() {
    return appInstanceId;
  }

  public void setAppInstanceId(String appInstanceId) {
    this.appInstanceId = appInstanceId;
  }

  public CellChangeSubscriptionFilterCriteriaAssocHo associateId(List<AssociateId> associateId) {
    this.associateId = associateId;
    return this;
  }

  public CellChangeSubscriptionFilterCriteriaAssocHo addAssociateIdItem(AssociateId associateIdItem) {
    if (this.associateId == null) {
      this.associateId = new ArrayList<AssociateId>();
    }
    this.associateId.add(associateIdItem);
    return this;
  }

   /**
   * 0 to N identifiers to associate the information for a specific UE or flow.
   * @return associateId
  **/
  @Schema(description = "0 to N identifiers to associate the information for a specific UE or flow.")
  public List<AssociateId> getAssociateId() {
    return associateId;
  }

  public void setAssociateId(List<AssociateId> associateId) {
    this.associateId = associateId;
  }

  public CellChangeSubscriptionFilterCriteriaAssocHo ecgi(List<Ecgi> ecgi) {
    this.ecgi = ecgi;
    return this;
  }

  public CellChangeSubscriptionFilterCriteriaAssocHo addEcgiItem(Ecgi ecgiItem) {
    if (this.ecgi == null) {
      this.ecgi = new ArrayList<Ecgi>();
    }
    this.ecgi.add(ecgiItem);
    return this;
  }

   /**
   * E-UTRAN Cell Global Identifier.
   * @return ecgi
  **/
  @Schema(description = "E-UTRAN Cell Global Identifier.")
  public List<Ecgi> getEcgi() {
    return ecgi;
  }

  public void setEcgi(List<Ecgi> ecgi) {
    this.ecgi = ecgi;
  }

  public CellChangeSubscriptionFilterCriteriaAssocHo hoStatus(List<Integer> hoStatus) {
    this.hoStatus = hoStatus;
    return this;
  }

  public CellChangeSubscriptionFilterCriteriaAssocHo addHoStatusItem(List<Integer> hoStatusItem) {
    if (this.hoStatus == null) {
      this.hoStatus = new ArrayList<Integer>();
    }
    for (Integer ho : hoStatusItem)
    this.hoStatus.add(ho);
    return this;
  }

   /**
   * In case hoStatus is not included in the subscription request, the default value 3 &#x3D; COMPLETED shall be used and included in the response: &lt;p&gt;1 &#x3D; IN_PREPARATION. &lt;p&gt;2 &#x3D; IN_EXECUTION. &lt;p&gt;3 &#x3D; COMPLETED. &lt;p&gt;4 &#x3D; REJECTED. &lt;p&gt;5 &#x3D; CANCELLED.
   * @return hoStatus
  **/
  @Schema(description = "In case hoStatus is not included in the subscription request, the default value 3 = COMPLETED shall be used and included in the response: <p>1 = IN_PREPARATION. <p>2 = IN_EXECUTION. <p>3 = COMPLETED. <p>4 = REJECTED. <p>5 = CANCELLED.")
  public List<Integer> getHoStatus() {
    return hoStatus;
  }

  public void setHoStatus(List<Integer> hoStatus) {
    this.hoStatus = hoStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CellChangeSubscriptionFilterCriteriaAssocHo cellChangeSubscriptionFilterCriteriaAssocHo = (CellChangeSubscriptionFilterCriteriaAssocHo) o;
    return Objects.equals(this.appInstanceId, cellChangeSubscriptionFilterCriteriaAssocHo.appInstanceId) &&
        Objects.equals(this.associateId, cellChangeSubscriptionFilterCriteriaAssocHo.associateId) &&
        Objects.equals(this.ecgi, cellChangeSubscriptionFilterCriteriaAssocHo.ecgi) &&
        Objects.equals(this.hoStatus, cellChangeSubscriptionFilterCriteriaAssocHo.hoStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appInstanceId, associateId, ecgi, hoStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CellChangeSubscriptionFilterCriteriaAssocHo {\n");
    
    sb.append("    appInstanceId: ").append(toIndentedString(appInstanceId)).append("\n");
    sb.append("    associateId: ").append(toIndentedString(associateId)).append("\n");
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    hoStatus: ").append(toIndentedString(hoStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
