/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * L2Meas
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class L2Meas {
  @SerializedName("cellInfo")
  private List<L2MeasCellInfo> cellInfo = null;

  @SerializedName("cellUEInfo")
  private List<L2MeasCellUEInfo> cellUEInfo = null;

  @SerializedName("timeStamp")
  private TimeStamp timeStamp = null;

  public L2Meas cellInfo(List<L2MeasCellInfo> cellInfo) {
    this.cellInfo = cellInfo;
    return this;
  }

  public L2Meas addCellInfoItem(L2MeasCellInfo cellInfoItem) {
    if (this.cellInfo == null) {
      this.cellInfo = new ArrayList<L2MeasCellInfo>();
    }
    this.cellInfo.add(cellInfoItem);
    return this;
  }

   /**
   * The per cell measurement information as defined below.
   * @return cellInfo
  **/
  @Schema(description = "The per cell measurement information as defined below.")
  public List<L2MeasCellInfo> getCellInfo() {
    return cellInfo;
  }

  public void setCellInfo(List<L2MeasCellInfo> cellInfo) {
    this.cellInfo = cellInfo;
  }

  public L2Meas cellUEInfo(List<L2MeasCellUEInfo> cellUEInfo) {
    this.cellUEInfo = cellUEInfo;
    return this;
  }

  public L2Meas addCellUEInfoItem(L2MeasCellUEInfo cellUEInfoItem) {
    if (this.cellUEInfo == null) {
      this.cellUEInfo = new ArrayList<L2MeasCellUEInfo>();
    }
    this.cellUEInfo.add(cellUEInfoItem);
    return this;
  }

   /**
   * The per cell per UE layer 2 measurements information as defined below.
   * @return cellUEInfo
  **/
  @Schema(description = "The per cell per UE layer 2 measurements information as defined below.")
  public List<L2MeasCellUEInfo> getCellUEInfo() {
    return cellUEInfo;
  }

  public void setCellUEInfo(List<L2MeasCellUEInfo> cellUEInfo) {
    this.cellUEInfo = cellUEInfo;
  }

  public L2Meas timeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @Schema(description = "")
  public TimeStamp getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    L2Meas l2Meas = (L2Meas) o;
    return Objects.equals(this.cellInfo, l2Meas.cellInfo) &&
        Objects.equals(this.cellUEInfo, l2Meas.cellUEInfo) &&
        Objects.equals(this.timeStamp, l2Meas.timeStamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cellInfo, cellUEInfo, timeStamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class L2Meas {\n");
    
    sb.append("    cellInfo: ").append(toIndentedString(cellInfo)).append("\n");
    sb.append("    cellUEInfo: ").append(toIndentedString(cellUEInfo)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
