/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MeasRepUeNotificationNrBNCsNrBNCellInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class MeasRepUeNotificationNrBNCsNrBNCellInfo {
  @SerializedName("nrBNCellGId")
  private String nrBNCellGId = null;

  @SerializedName("nrBNCellPlmn")
  private List<Plmn> nrBNCellPlmn = null;

  public MeasRepUeNotificationNrBNCsNrBNCellInfo nrBNCellGId(String nrBNCellGId) {
    this.nrBNCellGId = nrBNCellGId;
    return this;
  }

   /**
   * Get nrBNCellGId
   * @return nrBNCellGId
  **/
  @Schema(description = "")
  public String getNrBNCellGId() {
    return nrBNCellGId;
  }

  public void setNrBNCellGId(String nrBNCellGId) {
    this.nrBNCellGId = nrBNCellGId;
  }

  public MeasRepUeNotificationNrBNCsNrBNCellInfo nrBNCellPlmn(List<Plmn> nrBNCellPlmn) {
    this.nrBNCellPlmn = nrBNCellPlmn;
    return this;
  }

  public MeasRepUeNotificationNrBNCsNrBNCellInfo addNrBNCellPlmnItem(Plmn nrBNCellPlmnItem) {
    if (this.nrBNCellPlmn == null) {
      this.nrBNCellPlmn = new ArrayList<Plmn>();
    }
    this.nrBNCellPlmn.add(nrBNCellPlmnItem);
    return this;
  }

   /**
   * Public land mobile network identities
   * @return nrBNCellPlmn
  **/
  @Schema(description = "Public land mobile network identities")
  public List<Plmn> getNrBNCellPlmn() {
    return nrBNCellPlmn;
  }

  public void setNrBNCellPlmn(List<Plmn> nrBNCellPlmn) {
    this.nrBNCellPlmn = nrBNCellPlmn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasRepUeNotificationNrBNCsNrBNCellInfo measRepUeNotificationNrBNCsNrBNCellInfo = (MeasRepUeNotificationNrBNCsNrBNCellInfo) o;
    return Objects.equals(this.nrBNCellGId, measRepUeNotificationNrBNCsNrBNCellInfo.nrBNCellGId) &&
        Objects.equals(this.nrBNCellPlmn, measRepUeNotificationNrBNCsNrBNCellInfo.nrBNCellPlmn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nrBNCellGId, nrBNCellPlmn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasRepUeNotificationNrBNCsNrBNCellInfo {\n");
    
    sb.append("    nrBNCellGId: ").append(toIndentedString(nrBNCellGId)).append("\n");
    sb.append("    nrBNCellPlmn: ").append(toIndentedString(nrBNCellPlmn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
