/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MeasRepUeNotificationNrNCellInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class MeasRepUeNotificationNrNCellInfo {
  @SerializedName("nrNCellGId")
  private String nrNCellGId = null;

  @SerializedName("nrNCellPlmn")
  private List<Plmn> nrNCellPlmn = null;

  public MeasRepUeNotificationNrNCellInfo nrNCellGId(String nrNCellGId) {
    this.nrNCellGId = nrNCellGId;
    return this;
  }

   /**
   * Get nrNCellGId
   * @return nrNCellGId
  **/
  @Schema(description = "")
  public String getNrNCellGId() {
    return nrNCellGId;
  }

  public void setNrNCellGId(String nrNCellGId) {
    this.nrNCellGId = nrNCellGId;
  }

  public MeasRepUeNotificationNrNCellInfo nrNCellPlmn(List<Plmn> nrNCellPlmn) {
    this.nrNCellPlmn = nrNCellPlmn;
    return this;
  }

  public MeasRepUeNotificationNrNCellInfo addNrNCellPlmnItem(Plmn nrNCellPlmnItem) {
    if (this.nrNCellPlmn == null) {
      this.nrNCellPlmn = new ArrayList<Plmn>();
    }
    this.nrNCellPlmn.add(nrNCellPlmnItem);
    return this;
  }

   /**
   * Public land mobile network identities.
   * @return nrNCellPlmn
  **/
  @Schema(description = "Public land mobile network identities.")
  public List<Plmn> getNrNCellPlmn() {
    return nrNCellPlmn;
  }

  public void setNrNCellPlmn(List<Plmn> nrNCellPlmn) {
    this.nrNCellPlmn = nrNCellPlmn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasRepUeNotificationNrNCellInfo measRepUeNotificationNrNCellInfo = (MeasRepUeNotificationNrNCellInfo) o;
    return Objects.equals(this.nrNCellGId, measRepUeNotificationNrNCellInfo.nrNCellGId) &&
        Objects.equals(this.nrNCellPlmn, measRepUeNotificationNrNCellInfo.nrNCellPlmn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nrNCellGId, nrNCellPlmn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasRepUeNotificationNrNCellInfo {\n");
    
    sb.append("    nrNCellGId: ").append(toIndentedString(nrNCellGId)).append("\n");
    sb.append("    nrNCellPlmn: ").append(toIndentedString(nrNCellPlmn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
