/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * MeasRepUeNotificationEutranNeighbourCellMeasInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class MeasRepUeNotificationEutranNeighbourCellMeasInfo {
  @SerializedName("ecgi")
  private Ecgi ecgi = null;

  @SerializedName("rsrp")
  private Integer rsrp = null;

  @SerializedName("rsrpEx")
  private Integer rsrpEx = null;

  @SerializedName("rsrq")
  private Integer rsrq = null;

  @SerializedName("rsrqEx")
  private Integer rsrqEx = null;

  @SerializedName("sinr")
  private Integer sinr = null;

  public MeasRepUeNotificationEutranNeighbourCellMeasInfo ecgi(Ecgi ecgi) {
    this.ecgi = ecgi;
    return this;
  }

   /**
   * Get ecgi
   * @return ecgi
  **/
  @Schema(description = "")
  public Ecgi getEcgi() {
    return ecgi;
  }

  public void setEcgi(Ecgi ecgi) {
    this.ecgi = ecgi;
  }

  public MeasRepUeNotificationEutranNeighbourCellMeasInfo rsrp(Integer rsrp) {
    this.rsrp = rsrp;
    return this;
  }

   /**
   * Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].
   * @return rsrp
  **/
  @Schema(description = "Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].")
  public Integer getRsrp() {
    return rsrp;
  }

  public void setRsrp(Integer rsrp) {
    this.rsrp = rsrp;
  }

  public MeasRepUeNotificationEutranNeighbourCellMeasInfo rsrpEx(Integer rsrpEx) {
    this.rsrpEx = rsrpEx;
    return this;
  }

   /**
   * Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].
   * @return rsrpEx
  **/
  @Schema(description = "Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].")
  public Integer getRsrpEx() {
    return rsrpEx;
  }

  public void setRsrpEx(Integer rsrpEx) {
    this.rsrpEx = rsrpEx;
  }

  public MeasRepUeNotificationEutranNeighbourCellMeasInfo rsrq(Integer rsrq) {
    this.rsrq = rsrq;
    return this;
  }

   /**
   * Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].
   * @return rsrq
  **/
  @Schema(description = "Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].")
  public Integer getRsrq() {
    return rsrq;
  }

  public void setRsrq(Integer rsrq) {
    this.rsrq = rsrq;
  }

  public MeasRepUeNotificationEutranNeighbourCellMeasInfo rsrqEx(Integer rsrqEx) {
    this.rsrqEx = rsrqEx;
    return this;
  }

   /**
   * Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].
   * @return rsrqEx
  **/
  @Schema(description = "Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].")
  public Integer getRsrqEx() {
    return rsrqEx;
  }

  public void setRsrqEx(Integer rsrqEx) {
    this.rsrqEx = rsrqEx;
  }

  public MeasRepUeNotificationEutranNeighbourCellMeasInfo sinr(Integer sinr) {
    this.sinr = sinr;
    return this;
  }

   /**
   * Reference Signal \&quot;Signal to Interference plus Noise Ratio\&quot;, with value mapping defined in ETSI TS 136 133 [i.16].
   * @return sinr
  **/
  @Schema(description = "Reference Signal \"Signal to Interference plus Noise Ratio\", with value mapping defined in ETSI TS 136 133 [i.16].")
  public Integer getSinr() {
    return sinr;
  }

  public void setSinr(Integer sinr) {
    this.sinr = sinr;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasRepUeNotificationEutranNeighbourCellMeasInfo measRepUeNotificationEutranNeighbourCellMeasInfo = (MeasRepUeNotificationEutranNeighbourCellMeasInfo) o;
    return Objects.equals(this.ecgi, measRepUeNotificationEutranNeighbourCellMeasInfo.ecgi) &&
        Objects.equals(this.rsrp, measRepUeNotificationEutranNeighbourCellMeasInfo.rsrp) &&
        Objects.equals(this.rsrpEx, measRepUeNotificationEutranNeighbourCellMeasInfo.rsrpEx) &&
        Objects.equals(this.rsrq, measRepUeNotificationEutranNeighbourCellMeasInfo.rsrq) &&
        Objects.equals(this.rsrqEx, measRepUeNotificationEutranNeighbourCellMeasInfo.rsrqEx) &&
        Objects.equals(this.sinr, measRepUeNotificationEutranNeighbourCellMeasInfo.sinr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ecgi, rsrp, rsrpEx, rsrq, rsrqEx, sinr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasRepUeNotificationEutranNeighbourCellMeasInfo {\n");
    
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    rsrp: ").append(toIndentedString(rsrp)).append("\n");
    sb.append("    rsrpEx: ").append(toIndentedString(rsrpEx)).append("\n");
    sb.append("    rsrq: ").append(toIndentedString(rsrq)).append("\n");
    sb.append("    rsrqEx: ").append(toIndentedString(rsrqEx)).append("\n");
    sb.append("    sinr: ").append(toIndentedString(sinr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
