/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * List of filtering criteria for the subscription. Any filtering criteria from below, which is included in the request, shall also be included in the response.
 */
@Schema(description = "List of filtering criteria for the subscription. Any filtering criteria from below, which is included in the request, shall also be included in the response.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class MeasRepUeSubscriptionFilterCriteriaAssocTri {
  @SerializedName("appInstanceId")
  private String appInstanceId = null;

  @SerializedName("associateId")
  private List<AssociateId> associateId = null;

  @SerializedName("ecgi")
  private List<Ecgi> ecgi = null;

  @SerializedName("trigger")
  private List<Trigger> trigger = null;

  public MeasRepUeSubscriptionFilterCriteriaAssocTri appInstanceId(String appInstanceId) {
    this.appInstanceId = appInstanceId;
    return this;
  }

   /**
   * Unique identifier for the MEC application instance.
   * @return appInstanceId
  **/
  @Schema(description = "Unique identifier for the MEC application instance.")
  public String getAppInstanceId() {
    return appInstanceId;
  }

  public void setAppInstanceId(String appInstanceId) {
    this.appInstanceId = appInstanceId;
  }

  public MeasRepUeSubscriptionFilterCriteriaAssocTri associateId(List<AssociateId> associateId) {
    this.associateId = associateId;
    return this;
  }

  public MeasRepUeSubscriptionFilterCriteriaAssocTri addAssociateIdItem(AssociateId associateIdItem) {
    if (this.associateId == null) {
      this.associateId = new ArrayList<AssociateId>();
    }
    this.associateId.add(associateIdItem);
    return this;
  }

   /**
   * 0 to N identifiers to associate the information for a specific UE or flow.
   * @return associateId
  **/
  @Schema(description = "0 to N identifiers to associate the information for a specific UE or flow.")
  public List<AssociateId> getAssociateId() {
    return associateId;
  }

  public void setAssociateId(List<AssociateId> associateId) {
    this.associateId = associateId;
  }

  public MeasRepUeSubscriptionFilterCriteriaAssocTri ecgi(List<Ecgi> ecgi) {
    this.ecgi = ecgi;
    return this;
  }

  public MeasRepUeSubscriptionFilterCriteriaAssocTri addEcgiItem(Ecgi ecgiItem) {
    if (this.ecgi == null) {
      this.ecgi = new ArrayList<Ecgi>();
    }
    this.ecgi.add(ecgiItem);
    return this;
  }

   /**
   * E-UTRAN Cell Global Identifier.
   * @return ecgi
  **/
  @Schema(description = "E-UTRAN Cell Global Identifier.")
  public List<Ecgi> getEcgi() {
    return ecgi;
  }

  public void setEcgi(List<Ecgi> ecgi) {
    this.ecgi = ecgi;
  }

  public MeasRepUeSubscriptionFilterCriteriaAssocTri trigger(List<Trigger> trigger) {
    this.trigger = trigger;
    return this;
  }

  public MeasRepUeSubscriptionFilterCriteriaAssocTri addTriggerItem(Trigger triggerItem) {
    if (this.trigger == null) {
      this.trigger = new ArrayList<Trigger>();
    }
    this.trigger.add(triggerItem);
    return this;
  }

   /**
   * Corresponds to a specific E-UTRAN UE Measurement Report trigger.
   * @return trigger
  **/
  @Schema(description = "Corresponds to a specific E-UTRAN UE Measurement Report trigger.")
  public List<Trigger> getTrigger() {
    return trigger;
  }

  public void setTrigger(List<Trigger> trigger) {
    this.trigger = trigger;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasRepUeSubscriptionFilterCriteriaAssocTri measRepUeSubscriptionFilterCriteriaAssocTri = (MeasRepUeSubscriptionFilterCriteriaAssocTri) o;
    return Objects.equals(this.appInstanceId, measRepUeSubscriptionFilterCriteriaAssocTri.appInstanceId) &&
        Objects.equals(this.associateId, measRepUeSubscriptionFilterCriteriaAssocTri.associateId) &&
        Objects.equals(this.ecgi, measRepUeSubscriptionFilterCriteriaAssocTri.ecgi) &&
        Objects.equals(this.trigger, measRepUeSubscriptionFilterCriteriaAssocTri.trigger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appInstanceId, associateId, ecgi, trigger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasRepUeSubscriptionFilterCriteriaAssocTri {\n");
    
    sb.append("    appInstanceId: ").append(toIndentedString(appInstanceId)).append("\n");
    sb.append("    associateId: ").append(toIndentedString(associateId)).append("\n");
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
