/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * MeasRepUeNotificationNewRadioMeasInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class MeasRepUeNotificationNewRadioMeasInfo {
  @SerializedName("nrBNCs")
  private MeasRepUeNotificationNrBNCs nrBNCs = null;

  @SerializedName("nrCarrierFreq")
  private Integer nrCarrierFreq = null;

  @SerializedName("nrSCs")
  private MeasRepUeNotificationNrSCs nrSCs = null;

  public MeasRepUeNotificationNewRadioMeasInfo nrBNCs(MeasRepUeNotificationNrBNCs nrBNCs) {
    this.nrBNCs = nrBNCs;
    return this;
  }

   /**
   * Get nrBNCs
   * @return nrBNCs
  **/
  @Schema(description = "")
  public MeasRepUeNotificationNrBNCs getNrBNCs() {
    return nrBNCs;
  }

  public void setNrBNCs(MeasRepUeNotificationNrBNCs nrBNCs) {
    this.nrBNCs = nrBNCs;
  }

  public MeasRepUeNotificationNewRadioMeasInfo nrCarrierFreq(Integer nrCarrierFreq) {
    this.nrCarrierFreq = nrCarrierFreq;
    return this;
  }

   /**
   * ARFCN applicable for a downlink, uplink or bi-directional (TDD) NR carrier frequency, as defined in ETSI TS 138.101 [i.15].
   * @return nrCarrierFreq
  **/
  @Schema(description = "ARFCN applicable for a downlink, uplink or bi-directional (TDD) NR carrier frequency, as defined in ETSI TS 138.101 [i.15].")
  public Integer getNrCarrierFreq() {
    return nrCarrierFreq;
  }

  public void setNrCarrierFreq(Integer nrCarrierFreq) {
    this.nrCarrierFreq = nrCarrierFreq;
  }

  public MeasRepUeNotificationNewRadioMeasInfo nrSCs(MeasRepUeNotificationNrSCs nrSCs) {
    this.nrSCs = nrSCs;
    return this;
  }

   /**
   * Get nrSCs
   * @return nrSCs
  **/
  @Schema(description = "")
  public MeasRepUeNotificationNrSCs getNrSCs() {
    return nrSCs;
  }

  public void setNrSCs(MeasRepUeNotificationNrSCs nrSCs) {
    this.nrSCs = nrSCs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasRepUeNotificationNewRadioMeasInfo measRepUeNotificationNewRadioMeasInfo = (MeasRepUeNotificationNewRadioMeasInfo) o;
    return Objects.equals(this.nrBNCs, measRepUeNotificationNewRadioMeasInfo.nrBNCs) &&
        Objects.equals(this.nrCarrierFreq, measRepUeNotificationNewRadioMeasInfo.nrCarrierFreq) &&
        Objects.equals(this.nrSCs, measRepUeNotificationNewRadioMeasInfo.nrSCs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nrBNCs, nrCarrierFreq, nrSCs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasRepUeNotificationNewRadioMeasInfo {\n");
    
    sb.append("    nrBNCs: ").append(toIndentedString(nrBNCs)).append("\n");
    sb.append("    nrCarrierFreq: ").append(toIndentedString(nrCarrierFreq)).append("\n");
    sb.append("    nrSCs: ").append(toIndentedString(nrSCs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
