/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MeasTaNotification
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class MeasTaNotification implements OneOfInlineNotification {
  @SerializedName("associateId")
  private List<AssociateId> associateId = null;

  @SerializedName("ecgi")
  private Ecgi ecgi = null;

  @SerializedName("notificationType")
  private String notificationType = null;

  @SerializedName("timeStamp")
  private TimeStamp timeStamp = null;

  @SerializedName("timingAdvance")
  private Integer timingAdvance = null;

  public MeasTaNotification associateId(List<AssociateId> associateId) {
    this.associateId = associateId;
    return this;
  }

  public MeasTaNotification addAssociateIdItem(AssociateId associateIdItem) {
    if (this.associateId == null) {
      this.associateId = new ArrayList<AssociateId>();
    }
    this.associateId.add(associateIdItem);
    return this;
  }

   /**
   * 0 to N identifiers to associate the event for a specific UE or flow.
   * @return associateId
  **/
  @Schema(description = "0 to N identifiers to associate the event for a specific UE or flow.")
  public List<AssociateId> getAssociateId() {
    return associateId;
  }

  public void setAssociateId(List<AssociateId> associateId) {
    this.associateId = associateId;
  }

  public MeasTaNotification ecgi(Ecgi ecgi) {
    this.ecgi = ecgi;
    return this;
  }

   /**
   * Get ecgi
   * @return ecgi
  **/
  @Schema(required = true, description = "")
  public Ecgi getEcgi() {
    return ecgi;
  }

  public void setEcgi(Ecgi ecgi) {
    this.ecgi = ecgi;
  }

  public MeasTaNotification notificationType(String notificationType) {
    this.notificationType = notificationType;
    return this;
  }

   /**
   * Shall be set to \&quot;MeasTaNotification\&quot;.
   * @return notificationType
  **/
  @Schema(required = true, description = "Shall be set to \"MeasTaNotification\".")
  public String getNotificationType() {
    return notificationType;
  }

  public void setNotificationType(String notificationType) {
    this.notificationType = notificationType;
  }

  public MeasTaNotification timeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @Schema(description = "")
  public TimeStamp getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
  }

  public MeasTaNotification timingAdvance(Integer timingAdvance) {
    this.timingAdvance = timingAdvance;
    return this;
  }

   /**
   * The timing advance as defined in ETSI TS 136 214 [i.5].
   * @return timingAdvance
  **/
  @Schema(required = true, description = "The timing advance as defined in ETSI TS 136 214 [i.5].")
  public Integer getTimingAdvance() {
    return timingAdvance;
  }

  public void setTimingAdvance(Integer timingAdvance) {
    this.timingAdvance = timingAdvance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasTaNotification measTaNotification = (MeasTaNotification) o;
    return Objects.equals(this.associateId, measTaNotification.associateId) &&
        Objects.equals(this.ecgi, measTaNotification.ecgi) &&
        Objects.equals(this.notificationType, measTaNotification.notificationType) &&
        Objects.equals(this.timeStamp, measTaNotification.timeStamp) &&
        Objects.equals(this.timingAdvance, measTaNotification.timingAdvance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associateId, ecgi, notificationType, timeStamp, timingAdvance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasTaNotification {\n");
    
    sb.append("    associateId: ").append(toIndentedString(associateId)).append("\n");
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    notificationType: ").append(toIndentedString(notificationType)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    timingAdvance: ").append(toIndentedString(timingAdvance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
