/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MeasRepUeNotification
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class MeasRepUeNotification implements OneOfInlineNotification {
  @SerializedName("associateId")
  private List<AssociateId> associateId = null;

  @SerializedName("carrierAggregationMeasInfo")
  private List<MeasRepUeNotificationCarrierAggregationMeasInfo> carrierAggregationMeasInfo = null;

  @SerializedName("ecgi")
  private Ecgi ecgi = null;

  @SerializedName("eutranNeighbourCellMeasInfo")
  private List<MeasRepUeNotificationEutranNeighbourCellMeasInfo> eutranNeighbourCellMeasInfo = null;

  @SerializedName("heightUe")
  private Integer heightUe = null;

  @SerializedName("newRadioMeasInfo")
  private List<MeasRepUeNotificationNewRadioMeasInfo> newRadioMeasInfo = null;

  @SerializedName("newRadioMeasNeiInfo")
  private List<MeasRepUeNotificationNewRadioMeasNeiInfo> newRadioMeasNeiInfo = null;

  @SerializedName("notificationType")
  private String notificationType = null;

  @SerializedName("rsrp")
  private Integer rsrp = null;

  @SerializedName("rsrpEx")
  private Integer rsrpEx = null;

  @SerializedName("rsrq")
  private Integer rsrq = null;

  @SerializedName("rsrqEx")
  private Integer rsrqEx = null;

  @SerializedName("sinr")
  private Integer sinr = null;

  @SerializedName("timeStamp")
  private TimeStamp timeStamp = null;

  @SerializedName("trigger")
  private Trigger trigger = null;

  public MeasRepUeNotification associateId(List<AssociateId> associateId) {
    this.associateId = associateId;
    return this;
  }

  public MeasRepUeNotification addAssociateIdItem(AssociateId associateIdItem) {
    if (this.associateId == null) {
      this.associateId = new ArrayList<AssociateId>();
    }
    this.associateId.add(associateIdItem);
    return this;
  }

   /**
   * 0 to N identifiers to associate the event for a specific UE or flow.
   * @return associateId
  **/
  @Schema(description = "0 to N identifiers to associate the event for a specific UE or flow.")
  public List<AssociateId> getAssociateId() {
    return associateId;
  }

  public void setAssociateId(List<AssociateId> associateId) {
    this.associateId = associateId;
  }

  public MeasRepUeNotification carrierAggregationMeasInfo(List<MeasRepUeNotificationCarrierAggregationMeasInfo> carrierAggregationMeasInfo) {
    this.carrierAggregationMeasInfo = carrierAggregationMeasInfo;
    return this;
  }

  public MeasRepUeNotification addCarrierAggregationMeasInfoItem(MeasRepUeNotificationCarrierAggregationMeasInfo carrierAggregationMeasInfoItem) {
    if (this.carrierAggregationMeasInfo == null) {
      this.carrierAggregationMeasInfo = new ArrayList<MeasRepUeNotificationCarrierAggregationMeasInfo>();
    }
    this.carrierAggregationMeasInfo.add(carrierAggregationMeasInfoItem);
    return this;
  }

   /**
   * This parameter can be repeated to contain information of all the carriers assign for Carrier Aggregation up to M.
   * @return carrierAggregationMeasInfo
  **/
  @Schema(description = "This parameter can be repeated to contain information of all the carriers assign for Carrier Aggregation up to M.")
  public List<MeasRepUeNotificationCarrierAggregationMeasInfo> getCarrierAggregationMeasInfo() {
    return carrierAggregationMeasInfo;
  }

  public void setCarrierAggregationMeasInfo(List<MeasRepUeNotificationCarrierAggregationMeasInfo> carrierAggregationMeasInfo) {
    this.carrierAggregationMeasInfo = carrierAggregationMeasInfo;
  }

  public MeasRepUeNotification ecgi(Ecgi ecgi) {
    this.ecgi = ecgi;
    return this;
  }

   /**
   * Get ecgi
   * @return ecgi
  **/
  @Schema(required = true, description = "")
  public Ecgi getEcgi() {
    return ecgi;
  }

  public void setEcgi(Ecgi ecgi) {
    this.ecgi = ecgi;
  }

  public MeasRepUeNotification eutranNeighbourCellMeasInfo(List<MeasRepUeNotificationEutranNeighbourCellMeasInfo> eutranNeighbourCellMeasInfo) {
    this.eutranNeighbourCellMeasInfo = eutranNeighbourCellMeasInfo;
    return this;
  }

  public MeasRepUeNotification addEutranNeighbourCellMeasInfoItem(MeasRepUeNotificationEutranNeighbourCellMeasInfo eutranNeighbourCellMeasInfoItem) {
    if (this.eutranNeighbourCellMeasInfo == null) {
      this.eutranNeighbourCellMeasInfo = new ArrayList<MeasRepUeNotificationEutranNeighbourCellMeasInfo>();
    }
    this.eutranNeighbourCellMeasInfo.add(eutranNeighbourCellMeasInfoItem);
    return this;
  }

   /**
   * This parameter can be repeated to contain information of all the neighbouring cells up to N.
   * @return eutranNeighbourCellMeasInfo
  **/
  @Schema(description = "This parameter can be repeated to contain information of all the neighbouring cells up to N.")
  public List<MeasRepUeNotificationEutranNeighbourCellMeasInfo> getEutranNeighbourCellMeasInfo() {
    return eutranNeighbourCellMeasInfo;
  }

  public void setEutranNeighbourCellMeasInfo(List<MeasRepUeNotificationEutranNeighbourCellMeasInfo> eutranNeighbourCellMeasInfo) {
    this.eutranNeighbourCellMeasInfo = eutranNeighbourCellMeasInfo;
  }

  public MeasRepUeNotification heightUe(Integer heightUe) {
    this.heightUe = heightUe;
    return this;
  }

   /**
   * Indicates height of the UE in meters relative to the sea level as defined in ETSI TS 136.331 [i.7].
   * @return heightUe
  **/
  @Schema(description = "Indicates height of the UE in meters relative to the sea level as defined in ETSI TS 136.331 [i.7].")
  public Integer getHeightUe() {
    return heightUe;
  }

  public void setHeightUe(Integer heightUe) {
    this.heightUe = heightUe;
  }

  public MeasRepUeNotification newRadioMeasInfo(List<MeasRepUeNotificationNewRadioMeasInfo> newRadioMeasInfo) {
    this.newRadioMeasInfo = newRadioMeasInfo;
    return this;
  }

  public MeasRepUeNotification addNewRadioMeasInfoItem(MeasRepUeNotificationNewRadioMeasInfo newRadioMeasInfoItem) {
    if (this.newRadioMeasInfo == null) {
      this.newRadioMeasInfo = new ArrayList<MeasRepUeNotificationNewRadioMeasInfo>();
    }
    this.newRadioMeasInfo.add(newRadioMeasInfoItem);
    return this;
  }

   /**
   * 5G New Radio secondary serving cells measurement information.
   * @return newRadioMeasInfo
  **/
  @Schema(description = "5G New Radio secondary serving cells measurement information.")
  public List<MeasRepUeNotificationNewRadioMeasInfo> getNewRadioMeasInfo() {
    return newRadioMeasInfo;
  }

  public void setNewRadioMeasInfo(List<MeasRepUeNotificationNewRadioMeasInfo> newRadioMeasInfo) {
    this.newRadioMeasInfo = newRadioMeasInfo;
  }

  public MeasRepUeNotification newRadioMeasNeiInfo(List<MeasRepUeNotificationNewRadioMeasNeiInfo> newRadioMeasNeiInfo) {
    this.newRadioMeasNeiInfo = newRadioMeasNeiInfo;
    return this;
  }

  public MeasRepUeNotification addNewRadioMeasNeiInfoItem(MeasRepUeNotificationNewRadioMeasNeiInfo newRadioMeasNeiInfoItem) {
    if (this.newRadioMeasNeiInfo == null) {
      this.newRadioMeasNeiInfo = new ArrayList<MeasRepUeNotificationNewRadioMeasNeiInfo>();
    }
    this.newRadioMeasNeiInfo.add(newRadioMeasNeiInfoItem);
    return this;
  }

   /**
   * Measurement quantities concerning the 5G NR neighbours.
   * @return newRadioMeasNeiInfo
  **/
  @Schema(description = "Measurement quantities concerning the 5G NR neighbours.")
  public List<MeasRepUeNotificationNewRadioMeasNeiInfo> getNewRadioMeasNeiInfo() {
    return newRadioMeasNeiInfo;
  }

  public void setNewRadioMeasNeiInfo(List<MeasRepUeNotificationNewRadioMeasNeiInfo> newRadioMeasNeiInfo) {
    this.newRadioMeasNeiInfo = newRadioMeasNeiInfo;
  }

  public MeasRepUeNotification notificationType(String notificationType) {
    this.notificationType = notificationType;
    return this;
  }

   /**
   * Shall be set to \&quot;MeasRepUeNotification\&quot;.
   * @return notificationType
  **/
  @Schema(required = true, description = "Shall be set to \"MeasRepUeNotification\".")
  public String getNotificationType() {
    return notificationType;
  }

  public void setNotificationType(String notificationType) {
    this.notificationType = notificationType;
  }

  public MeasRepUeNotification rsrp(Integer rsrp) {
    this.rsrp = rsrp;
    return this;
  }

   /**
   * Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].
   * @return rsrp
  **/
  @Schema(required = true, description = "Reference Signal Received Power as defined in ETSI TS 136 214 [i.5].")
  public Integer getRsrp() {
    return rsrp;
  }

  public void setRsrp(Integer rsrp) {
    this.rsrp = rsrp;
  }

  public MeasRepUeNotification rsrpEx(Integer rsrpEx) {
    this.rsrpEx = rsrpEx;
    return this;
  }

   /**
   * Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].
   * @return rsrpEx
  **/
  @Schema(description = "Extended Reference Signal Received Power, with value mapping defined in ETSI TS 136 133 [i.16].")
  public Integer getRsrpEx() {
    return rsrpEx;
  }

  public void setRsrpEx(Integer rsrpEx) {
    this.rsrpEx = rsrpEx;
  }

  public MeasRepUeNotification rsrq(Integer rsrq) {
    this.rsrq = rsrq;
    return this;
  }

   /**
   * Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].
   * @return rsrq
  **/
  @Schema(required = true, description = "Reference Signal Received Quality as defined in ETSI TS 136 214 [i.5].")
  public Integer getRsrq() {
    return rsrq;
  }

  public void setRsrq(Integer rsrq) {
    this.rsrq = rsrq;
  }

  public MeasRepUeNotification rsrqEx(Integer rsrqEx) {
    this.rsrqEx = rsrqEx;
    return this;
  }

   /**
   * Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].
   * @return rsrqEx
  **/
  @Schema(description = "Extended Reference Signal Received Quality, with value mapping defined in ETSI TS 136 133 [i.16].")
  public Integer getRsrqEx() {
    return rsrqEx;
  }

  public void setRsrqEx(Integer rsrqEx) {
    this.rsrqEx = rsrqEx;
  }

  public MeasRepUeNotification sinr(Integer sinr) {
    this.sinr = sinr;
    return this;
  }

   /**
   * Reference Signal \&quot;Signal to Interference plus Noise Ratio\&quot;, with value mapping defined in ETSI TS 136 133 [i.16].
   * @return sinr
  **/
  @Schema(description = "Reference Signal \"Signal to Interference plus Noise Ratio\", with value mapping defined in ETSI TS 136 133 [i.16].")
  public Integer getSinr() {
    return sinr;
  }

  public void setSinr(Integer sinr) {
    this.sinr = sinr;
  }

  public MeasRepUeNotification timeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @Schema(description = "")
  public TimeStamp getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
  }

  public MeasRepUeNotification trigger(Trigger trigger) {
    this.trigger = trigger;
    return this;
  }

   /**
   * Get trigger
   * @return trigger
  **/
  @Schema(required = true, description = "")
  public Trigger getTrigger() {
    return trigger;
  }

  public void setTrigger(Trigger trigger) {
    this.trigger = trigger;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasRepUeNotification measRepUeNotification = (MeasRepUeNotification) o;
    return Objects.equals(this.associateId, measRepUeNotification.associateId) &&
        Objects.equals(this.carrierAggregationMeasInfo, measRepUeNotification.carrierAggregationMeasInfo) &&
        Objects.equals(this.ecgi, measRepUeNotification.ecgi) &&
        Objects.equals(this.eutranNeighbourCellMeasInfo, measRepUeNotification.eutranNeighbourCellMeasInfo) &&
        Objects.equals(this.heightUe, measRepUeNotification.heightUe) &&
        Objects.equals(this.newRadioMeasInfo, measRepUeNotification.newRadioMeasInfo) &&
        Objects.equals(this.newRadioMeasNeiInfo, measRepUeNotification.newRadioMeasNeiInfo) &&
        Objects.equals(this.notificationType, measRepUeNotification.notificationType) &&
        Objects.equals(this.rsrp, measRepUeNotification.rsrp) &&
        Objects.equals(this.rsrpEx, measRepUeNotification.rsrpEx) &&
        Objects.equals(this.rsrq, measRepUeNotification.rsrq) &&
        Objects.equals(this.rsrqEx, measRepUeNotification.rsrqEx) &&
        Objects.equals(this.sinr, measRepUeNotification.sinr) &&
        Objects.equals(this.timeStamp, measRepUeNotification.timeStamp) &&
        Objects.equals(this.trigger, measRepUeNotification.trigger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associateId, carrierAggregationMeasInfo, ecgi, eutranNeighbourCellMeasInfo, heightUe, newRadioMeasInfo, newRadioMeasNeiInfo, notificationType, rsrp, rsrpEx, rsrq, rsrqEx, sinr, timeStamp, trigger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasRepUeNotification {\n");
    
    sb.append("    associateId: ").append(toIndentedString(associateId)).append("\n");
    sb.append("    carrierAggregationMeasInfo: ").append(toIndentedString(carrierAggregationMeasInfo)).append("\n");
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    eutranNeighbourCellMeasInfo: ").append(toIndentedString(eutranNeighbourCellMeasInfo)).append("\n");
    sb.append("    heightUe: ").append(toIndentedString(heightUe)).append("\n");
    sb.append("    newRadioMeasInfo: ").append(toIndentedString(newRadioMeasInfo)).append("\n");
    sb.append("    newRadioMeasNeiInfo: ").append(toIndentedString(newRadioMeasNeiInfo)).append("\n");
    sb.append("    notificationType: ").append(toIndentedString(notificationType)).append("\n");
    sb.append("    rsrp: ").append(toIndentedString(rsrp)).append("\n");
    sb.append("    rsrpEx: ").append(toIndentedString(rsrpEx)).append("\n");
    sb.append("    rsrq: ").append(toIndentedString(rsrq)).append("\n");
    sb.append("    rsrqEx: ").append(toIndentedString(rsrqEx)).append("\n");
    sb.append("    sinr: ").append(toIndentedString(sinr)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
