/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * NRcgi
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class NRcgi {
  @SerializedName("nrcellId")
  private String nrcellId = null;

  @SerializedName("plmn")
  private Plmn plmn = null;

  public NRcgi nrcellId(String nrcellId) {
    this.nrcellId = nrcellId;
    return this;
  }

   /**
   * Get nrcellId
   * @return nrcellId
  **/
  @Schema(required = true, description = "")
  public String getNrcellId() {
    return nrcellId;
  }

  public void setNrcellId(String nrcellId) {
    this.nrcellId = nrcellId;
  }

  public NRcgi plmn(Plmn plmn) {
    this.plmn = plmn;
    return this;
  }

   /**
   * Get plmn
   * @return plmn
  **/
  @Schema(required = true, description = "")
  public Plmn getPlmn() {
    return plmn;
  }

  public void setPlmn(Plmn plmn) {
    this.plmn = plmn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NRcgi nrcgi = (NRcgi) o;
    return Objects.equals(this.nrcellId, nrcgi.nrcellId) &&
        Objects.equals(this.plmn, nrcgi.plmn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nrcellId, plmn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NRcgi {\n");
    
    sb.append("    nrcellId: ").append(toIndentedString(nrcellId)).append("\n");
    sb.append("    plmn: ").append(toIndentedString(plmn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
