/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Measurement information relating to this serving cell.
 */
@Schema(description = "Measurement information relating to this serving cell.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class NrMeasRepUeNotificationSCell {
  @SerializedName("measQuantityResultsCsiRsCell")
  private MeasQuantityResultsNr measQuantityResultsCsiRsCell = null;

  @SerializedName("measQuantityResultsSsbCell")
  private MeasQuantityResultsNr measQuantityResultsSsbCell = null;

  @SerializedName("rsIndexResults")
  private RsIndexResults rsIndexResults = null;

  public NrMeasRepUeNotificationSCell measQuantityResultsCsiRsCell(MeasQuantityResultsNr measQuantityResultsCsiRsCell) {
    this.measQuantityResultsCsiRsCell = measQuantityResultsCsiRsCell;
    return this;
  }

   /**
   * Get measQuantityResultsCsiRsCell
   * @return measQuantityResultsCsiRsCell
  **/
  @Schema(description = "")
  public MeasQuantityResultsNr getMeasQuantityResultsCsiRsCell() {
    return measQuantityResultsCsiRsCell;
  }

  public void setMeasQuantityResultsCsiRsCell(MeasQuantityResultsNr measQuantityResultsCsiRsCell) {
    this.measQuantityResultsCsiRsCell = measQuantityResultsCsiRsCell;
  }

  public NrMeasRepUeNotificationSCell measQuantityResultsSsbCell(MeasQuantityResultsNr measQuantityResultsSsbCell) {
    this.measQuantityResultsSsbCell = measQuantityResultsSsbCell;
    return this;
  }

   /**
   * Get measQuantityResultsSsbCell
   * @return measQuantityResultsSsbCell
  **/
  @Schema(description = "")
  public MeasQuantityResultsNr getMeasQuantityResultsSsbCell() {
    return measQuantityResultsSsbCell;
  }

  public void setMeasQuantityResultsSsbCell(MeasQuantityResultsNr measQuantityResultsSsbCell) {
    this.measQuantityResultsSsbCell = measQuantityResultsSsbCell;
  }

  public NrMeasRepUeNotificationSCell rsIndexResults(RsIndexResults rsIndexResults) {
    this.rsIndexResults = rsIndexResults;
    return this;
  }

   /**
   * Get rsIndexResults
   * @return rsIndexResults
  **/
  @Schema(description = "")
  public RsIndexResults getRsIndexResults() {
    return rsIndexResults;
  }

  public void setRsIndexResults(RsIndexResults rsIndexResults) {
    this.rsIndexResults = rsIndexResults;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NrMeasRepUeNotificationSCell nrMeasRepUeNotificationSCell = (NrMeasRepUeNotificationSCell) o;
    return Objects.equals(this.measQuantityResultsCsiRsCell, nrMeasRepUeNotificationSCell.measQuantityResultsCsiRsCell) &&
        Objects.equals(this.measQuantityResultsSsbCell, nrMeasRepUeNotificationSCell.measQuantityResultsSsbCell) &&
        Objects.equals(this.rsIndexResults, nrMeasRepUeNotificationSCell.rsIndexResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(measQuantityResultsCsiRsCell, measQuantityResultsSsbCell, rsIndexResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NrMeasRepUeNotificationSCell {\n");
    
    sb.append("    measQuantityResultsCsiRsCell: ").append(toIndentedString(measQuantityResultsCsiRsCell)).append("\n");
    sb.append("    measQuantityResultsSsbCell: ").append(toIndentedString(measQuantityResultsSsbCell)).append("\n");
    sb.append("    rsIndexResults: ").append(toIndentedString(rsIndexResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
