/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * NrMeasRepUeNotification
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class NrMeasRepUeNotification implements OneOfInlineNotification {
  @SerializedName("associateId")
  private List<AssociateId> associateId = null;

  @SerializedName("eutraNeighCellMeasInfo")
  private List<NrMeasRepUeNotificationEutraNeighCellMeasInfo> eutraNeighCellMeasInfo = null;

  @SerializedName("notificationType")
  private String notificationType = null;

  @SerializedName("nrNeighCellMeasInfo")
  private List<NrMeasRepUeNotificationNrNeighCellMeasInfo> nrNeighCellMeasInfo = null;

  @SerializedName("servCellMeasInfo")
  private List<NrMeasRepUeNotificationServCellMeasInfo> servCellMeasInfo = null;

  @SerializedName("timeStamp")
  private TimeStamp timeStamp = null;

  @SerializedName("triggerNr")
  private TriggerNr triggerNr = null;

  public NrMeasRepUeNotification associateId(List<AssociateId> associateId) {
    this.associateId = associateId;
    return this;
  }

  public NrMeasRepUeNotification addAssociateIdItem(AssociateId associateIdItem) {
    if (this.associateId == null) {
      this.associateId = new ArrayList<AssociateId>();
    }
    this.associateId.add(associateIdItem);
    return this;
  }

   /**
   * 0 to N identifiers to associate the event for a specific UE or flow.
   * @return associateId
  **/
  @Schema(description = "0 to N identifiers to associate the event for a specific UE or flow.")
  public List<AssociateId> getAssociateId() {
    return associateId;
  }

  public void setAssociateId(List<AssociateId> associateId) {
    this.associateId = associateId;
  }

  public NrMeasRepUeNotification eutraNeighCellMeasInfo(List<NrMeasRepUeNotificationEutraNeighCellMeasInfo> eutraNeighCellMeasInfo) {
    this.eutraNeighCellMeasInfo = eutraNeighCellMeasInfo;
    return this;
  }

  public NrMeasRepUeNotification addEutraNeighCellMeasInfoItem(NrMeasRepUeNotificationEutraNeighCellMeasInfo eutraNeighCellMeasInfoItem) {
    if (this.eutraNeighCellMeasInfo == null) {
      this.eutraNeighCellMeasInfo = new ArrayList<NrMeasRepUeNotificationEutraNeighCellMeasInfo>();
    }
    this.eutraNeighCellMeasInfo.add(eutraNeighCellMeasInfoItem);
    return this;
  }

   /**
   * This parameter can be repeated to contain measurement information of all the neighbouring cells up to N. It shall not be included if nrNeighCellMeasInfo is included.
   * @return eutraNeighCellMeasInfo
  **/
  @Schema(description = "This parameter can be repeated to contain measurement information of all the neighbouring cells up to N. It shall not be included if nrNeighCellMeasInfo is included.")
  public List<NrMeasRepUeNotificationEutraNeighCellMeasInfo> getEutraNeighCellMeasInfo() {
    return eutraNeighCellMeasInfo;
  }

  public void setEutraNeighCellMeasInfo(List<NrMeasRepUeNotificationEutraNeighCellMeasInfo> eutraNeighCellMeasInfo) {
    this.eutraNeighCellMeasInfo = eutraNeighCellMeasInfo;
  }

  public NrMeasRepUeNotification notificationType(String notificationType) {
    this.notificationType = notificationType;
    return this;
  }

   /**
   * Shall be set to \&quot;NrMeasRepUeNotification\&quot;.
   * @return notificationType
  **/
  @Schema(required = true, description = "Shall be set to \"NrMeasRepUeNotification\".")
  public String getNotificationType() {
    return notificationType;
  }

  public void setNotificationType(String notificationType) {
    this.notificationType = notificationType;
  }

  public NrMeasRepUeNotification nrNeighCellMeasInfo(List<NrMeasRepUeNotificationNrNeighCellMeasInfo> nrNeighCellMeasInfo) {
    this.nrNeighCellMeasInfo = nrNeighCellMeasInfo;
    return this;
  }

  public NrMeasRepUeNotification addNrNeighCellMeasInfoItem(NrMeasRepUeNotificationNrNeighCellMeasInfo nrNeighCellMeasInfoItem) {
    if (this.nrNeighCellMeasInfo == null) {
      this.nrNeighCellMeasInfo = new ArrayList<NrMeasRepUeNotificationNrNeighCellMeasInfo>();
    }
    this.nrNeighCellMeasInfo.add(nrNeighCellMeasInfoItem);
    return this;
  }

   /**
   * This parameter can be repeated to contain measurement information of all the neighbouring cells up to N. It shall not be included if eutraNeighCellMeasInfo is included.
   * @return nrNeighCellMeasInfo
  **/
  @Schema(description = "This parameter can be repeated to contain measurement information of all the neighbouring cells up to N. It shall not be included if eutraNeighCellMeasInfo is included.")
  public List<NrMeasRepUeNotificationNrNeighCellMeasInfo> getNrNeighCellMeasInfo() {
    return nrNeighCellMeasInfo;
  }

  public void setNrNeighCellMeasInfo(List<NrMeasRepUeNotificationNrNeighCellMeasInfo> nrNeighCellMeasInfo) {
    this.nrNeighCellMeasInfo = nrNeighCellMeasInfo;
  }

  public NrMeasRepUeNotification servCellMeasInfo(List<NrMeasRepUeNotificationServCellMeasInfo> servCellMeasInfo) {
    this.servCellMeasInfo = servCellMeasInfo;
    return this;
  }

  public NrMeasRepUeNotification addServCellMeasInfoItem(NrMeasRepUeNotificationServCellMeasInfo servCellMeasInfoItem) {
    if (this.servCellMeasInfo == null) {
      this.servCellMeasInfo = new ArrayList<NrMeasRepUeNotificationServCellMeasInfo>();
    }
    this.servCellMeasInfo.add(servCellMeasInfoItem);
    return this;
  }

   /**
   * This parameter can be repeated to contain information of all the serving cells up to N.
   * @return servCellMeasInfo
  **/
  @Schema(description = "This parameter can be repeated to contain information of all the serving cells up to N.")
  public List<NrMeasRepUeNotificationServCellMeasInfo> getServCellMeasInfo() {
    return servCellMeasInfo;
  }

  public void setServCellMeasInfo(List<NrMeasRepUeNotificationServCellMeasInfo> servCellMeasInfo) {
    this.servCellMeasInfo = servCellMeasInfo;
  }

  public NrMeasRepUeNotification timeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @Schema(description = "")
  public TimeStamp getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
  }

  public NrMeasRepUeNotification triggerNr(TriggerNr triggerNr) {
    this.triggerNr = triggerNr;
    return this;
  }

   /**
   * Get triggerNr
   * @return triggerNr
  **/
  @Schema(required = true, description = "")
  public TriggerNr getTriggerNr() {
    return triggerNr;
  }

  public void setTriggerNr(TriggerNr triggerNr) {
    this.triggerNr = triggerNr;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NrMeasRepUeNotification nrMeasRepUeNotification = (NrMeasRepUeNotification) o;
    return Objects.equals(this.associateId, nrMeasRepUeNotification.associateId) &&
        Objects.equals(this.eutraNeighCellMeasInfo, nrMeasRepUeNotification.eutraNeighCellMeasInfo) &&
        Objects.equals(this.notificationType, nrMeasRepUeNotification.notificationType) &&
        Objects.equals(this.nrNeighCellMeasInfo, nrMeasRepUeNotification.nrNeighCellMeasInfo) &&
        Objects.equals(this.servCellMeasInfo, nrMeasRepUeNotification.servCellMeasInfo) &&
        Objects.equals(this.timeStamp, nrMeasRepUeNotification.timeStamp) &&
        Objects.equals(this.triggerNr, nrMeasRepUeNotification.triggerNr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associateId, eutraNeighCellMeasInfo, notificationType, nrNeighCellMeasInfo, servCellMeasInfo, timeStamp, triggerNr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NrMeasRepUeNotification {\n");
    
    sb.append("    associateId: ").append(toIndentedString(associateId)).append("\n");
    sb.append("    eutraNeighCellMeasInfo: ").append(toIndentedString(eutraNeighCellMeasInfo)).append("\n");
    sb.append("    notificationType: ").append(toIndentedString(notificationType)).append("\n");
    sb.append("    nrNeighCellMeasInfo: ").append(toIndentedString(nrNeighCellMeasInfo)).append("\n");
    sb.append("    servCellMeasInfo: ").append(toIndentedString(servCellMeasInfo)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    triggerNr: ").append(toIndentedString(triggerNr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
