/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * NrMeasRepUeNotificationEutraNeighCellMeasInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class NrMeasRepUeNotificationEutraNeighCellMeasInfo {
  @SerializedName("ecgi")
  private Ecgi ecgi = null;

  @SerializedName("rsrp")
  private Integer rsrp = null;

  @SerializedName("rsrq")
  private Integer rsrq = null;

  @SerializedName("sinr")
  private Integer sinr = null;

  public NrMeasRepUeNotificationEutraNeighCellMeasInfo ecgi(Ecgi ecgi) {
    this.ecgi = ecgi;
    return this;
  }

   /**
   * Get ecgi
   * @return ecgi
  **/
  @Schema(description = "")
  public Ecgi getEcgi() {
    return ecgi;
  }

  public void setEcgi(Ecgi ecgi) {
    this.ecgi = ecgi;
  }

  public NrMeasRepUeNotificationEutraNeighCellMeasInfo rsrp(Integer rsrp) {
    this.rsrp = rsrp;
    return this;
  }

   /**
   * Reference Signal Received Power as defined in ETSI TS 138 331 [i.13].
   * @return rsrp
  **/
  @Schema(description = "Reference Signal Received Power as defined in ETSI TS 138 331 [i.13].")
  public Integer getRsrp() {
    return rsrp;
  }

  public void setRsrp(Integer rsrp) {
    this.rsrp = rsrp;
  }

  public NrMeasRepUeNotificationEutraNeighCellMeasInfo rsrq(Integer rsrq) {
    this.rsrq = rsrq;
    return this;
  }

   /**
   * Reference Signal Received Quality as defined in ETSI TS 138 331 [i.13].
   * @return rsrq
  **/
  @Schema(description = "Reference Signal Received Quality as defined in ETSI TS 138 331 [i.13].")
  public Integer getRsrq() {
    return rsrq;
  }

  public void setRsrq(Integer rsrq) {
    this.rsrq = rsrq;
  }

  public NrMeasRepUeNotificationEutraNeighCellMeasInfo sinr(Integer sinr) {
    this.sinr = sinr;
    return this;
  }

   /**
   * Reference Signal plus Interference Noise Ratio as defined in ETSI TS 138 331 [i.13].
   * @return sinr
  **/
  @Schema(description = "Reference Signal plus Interference Noise Ratio as defined in ETSI TS 138 331 [i.13].")
  public Integer getSinr() {
    return sinr;
  }

  public void setSinr(Integer sinr) {
    this.sinr = sinr;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NrMeasRepUeNotificationEutraNeighCellMeasInfo nrMeasRepUeNotificationEutraNeighCellMeasInfo = (NrMeasRepUeNotificationEutraNeighCellMeasInfo) o;
    return Objects.equals(this.ecgi, nrMeasRepUeNotificationEutraNeighCellMeasInfo.ecgi) &&
        Objects.equals(this.rsrp, nrMeasRepUeNotificationEutraNeighCellMeasInfo.rsrp) &&
        Objects.equals(this.rsrq, nrMeasRepUeNotificationEutraNeighCellMeasInfo.rsrq) &&
        Objects.equals(this.sinr, nrMeasRepUeNotificationEutraNeighCellMeasInfo.sinr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ecgi, rsrp, rsrq, sinr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NrMeasRepUeNotificationEutraNeighCellMeasInfo {\n");
    
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    rsrp: ").append(toIndentedString(rsrp)).append("\n");
    sb.append("    rsrq: ").append(toIndentedString(rsrq)).append("\n");
    sb.append("    sinr: ").append(toIndentedString(sinr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
