/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * NrMeasRepUeNotificationServCellMeasInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class NrMeasRepUeNotificationServCellMeasInfo {
  @SerializedName("nCell")
  private NrMeasRepUeNotificationNCell nCell = null;

  @SerializedName("nrcgi")
  private NRcgi nrcgi = null;

  @SerializedName("sCell")
  private NrMeasRepUeNotificationSCell sCell = null;

  public NrMeasRepUeNotificationServCellMeasInfo nCell(NrMeasRepUeNotificationNCell nCell) {
    this.nCell = nCell;
    return this;
  }

   /**
   * Get nCell
   * @return nCell
  **/
  @Schema(description = "")
  public NrMeasRepUeNotificationNCell getNCell() {
    return nCell;
  }

  public void setNCell(NrMeasRepUeNotificationNCell nCell) {
    this.nCell = nCell;
  }

  public NrMeasRepUeNotificationServCellMeasInfo nrcgi(NRcgi nrcgi) {
    this.nrcgi = nrcgi;
    return this;
  }

   /**
   * Get nrcgi
   * @return nrcgi
  **/
  @Schema(description = "")
  public NRcgi getNrcgi() {
    return nrcgi;
  }

  public void setNrcgi(NRcgi nrcgi) {
    this.nrcgi = nrcgi;
  }

  public NrMeasRepUeNotificationServCellMeasInfo sCell(NrMeasRepUeNotificationSCell sCell) {
    this.sCell = sCell;
    return this;
  }

   /**
   * Get sCell
   * @return sCell
  **/
  @Schema(description = "")
  public NrMeasRepUeNotificationSCell getSCell() {
    return sCell;
  }

  public void setSCell(NrMeasRepUeNotificationSCell sCell) {
    this.sCell = sCell;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NrMeasRepUeNotificationServCellMeasInfo nrMeasRepUeNotificationServCellMeasInfo = (NrMeasRepUeNotificationServCellMeasInfo) o;
    return Objects.equals(this.nCell, nrMeasRepUeNotificationServCellMeasInfo.nCell) &&
        Objects.equals(this.nrcgi, nrMeasRepUeNotificationServCellMeasInfo.nrcgi) &&
        Objects.equals(this.sCell, nrMeasRepUeNotificationServCellMeasInfo.sCell);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nCell, nrcgi, sCell);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NrMeasRepUeNotificationServCellMeasInfo {\n");
    
    sb.append("    nCell: ").append(toIndentedString(nCell)).append("\n");
    sb.append("    nrcgi: ").append(toIndentedString(nrcgi)).append("\n");
    sb.append("    sCell: ").append(toIndentedString(sCell)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
