/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Plmn
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class Plmn {
  @SerializedName("mcc")
  private String mcc = null;

  @SerializedName("mnc")
  private String mnc = null;

  public Plmn mcc(String mcc) {
    this.mcc = mcc;
    return this;
  }

   /**
   * The Mobile Country Code part of PLMN Identity as defined in ETSI TS 136 413 [i.3].
   * @return mcc
  **/
  @Schema(required = true, description = "The Mobile Country Code part of PLMN Identity as defined in ETSI TS 136 413 [i.3].")
  public String getMcc() {
    return mcc;
  }

  public void setMcc(String mcc) {
    this.mcc = mcc;
  }

  public Plmn mnc(String mnc) {
    this.mnc = mnc;
    return this;
  }

   /**
   * The Mobile Network Code part of PLMN Identity as defined in ETSI TS 136 413 [i.3].
   * @return mnc
  **/
  @Schema(required = true, description = "The Mobile Network Code part of PLMN Identity as defined in ETSI TS 136 413 [i.3].")
  public String getMnc() {
    return mnc;
  }

  public void setMnc(String mnc) {
    this.mnc = mnc;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Plmn plmn = (Plmn) o;
    return Objects.equals(this.mcc, plmn.mcc) &&
        Objects.equals(this.mnc, plmn.mnc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mcc, mnc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Plmn {\n");
    
    sb.append("    mcc: ").append(toIndentedString(mcc)).append("\n");
    sb.append("    mnc: ").append(toIndentedString(mnc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
