/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PlmnInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class PlmnInfo {
  @SerializedName("appInstanceId")
  private String appInstanceId = null;

  @SerializedName("plmn")
  private List<Plmn> plmn = new ArrayList<Plmn>();

  @SerializedName("timeStamp")
  private TimeStamp timeStamp = null;

  public PlmnInfo appInstanceId(String appInstanceId) {
    this.appInstanceId = appInstanceId;
    return this;
  }

   /**
   * Unique identifier for the MEC application instance.
   * @return appInstanceId
  **/
  @Schema(required = true, description = "Unique identifier for the MEC application instance.")
  public String getAppInstanceId() {
    return appInstanceId;
  }

  public void setAppInstanceId(String appInstanceId) {
    this.appInstanceId = appInstanceId;
  }

  public PlmnInfo plmn(List<Plmn> plmn) {
    this.plmn = plmn;
    return this;
  }

  public PlmnInfo addPlmnItem(Plmn plmnItem) {
    this.plmn.add(plmnItem);
    return this;
  }

   /**
   * Public Land Mobile Network Identity.
   * @return plmn
  **/
  @Schema(required = true, description = "Public Land Mobile Network Identity.")
  public List<Plmn> getPlmn() {
    return plmn;
  }

  public void setPlmn(List<Plmn> plmn) {
    this.plmn = plmn;
  }

  public PlmnInfo timeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @Schema(description = "")
  public TimeStamp getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlmnInfo plmnInfo = (PlmnInfo) o;
    return Objects.equals(this.appInstanceId, plmnInfo.appInstanceId) &&
        Objects.equals(this.plmn, plmnInfo.plmn) &&
        Objects.equals(this.timeStamp, plmnInfo.timeStamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appInstanceId, plmn, timeStamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlmnInfo {\n");
    
    sb.append("    appInstanceId: ").append(toIndentedString(appInstanceId)).append("\n");
    sb.append("    plmn: ").append(toIndentedString(plmn)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
