/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * RabInfoCellUserInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class RabInfoCellUserInfo {
  @SerializedName("ecgi")
  private Ecgi ecgi = null;

  @SerializedName("ueInfo")
  private List<RabInfoUeInfo> ueInfo = null;

  public RabInfoCellUserInfo ecgi(Ecgi ecgi) {
    this.ecgi = ecgi;
    return this;
  }

   /**
   * Get ecgi
   * @return ecgi
  **/
  @Schema(description = "")
  public Ecgi getEcgi() {
    return ecgi;
  }

  public void setEcgi(Ecgi ecgi) {
    this.ecgi = ecgi;
  }

  public RabInfoCellUserInfo ueInfo(List<RabInfoUeInfo> ueInfo) {
    this.ueInfo = ueInfo;
    return this;
  }

  public RabInfoCellUserInfo addUeInfoItem(RabInfoUeInfo ueInfoItem) {
    if (this.ueInfo == null) {
      this.ueInfo = new ArrayList<RabInfoUeInfo>();
    }
    this.ueInfo.add(ueInfoItem);
    return this;
  }

   /**
   * Information on UEs in the specific cell as defined below.
   * @return ueInfo
  **/
  @Schema(description = "Information on UEs in the specific cell as defined below.")
  public List<RabInfoUeInfo> getUeInfo() {
    return ueInfo;
  }

  public void setUeInfo(List<RabInfoUeInfo> ueInfo) {
    this.ueInfo = ueInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RabInfoCellUserInfo rabInfoCellUserInfo = (RabInfoCellUserInfo) o;
    return Objects.equals(this.ecgi, rabInfoCellUserInfo.ecgi) &&
        Objects.equals(this.ueInfo, rabInfoCellUserInfo.ueInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ecgi, ueInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RabInfoCellUserInfo {\n");
    
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    ueInfo: ").append(toIndentedString(ueInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
