/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * RabInfoUeInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class RabInfoUeInfo {
  @SerializedName("associateId")
  private List<AssociateId> associateId = null;

  @SerializedName("erabInfo")
  private List<RabInfoErabInfo> erabInfo = null;

  public RabInfoUeInfo associateId(List<AssociateId> associateId) {
    this.associateId = associateId;
    return this;
  }

  public RabInfoUeInfo addAssociateIdItem(AssociateId associateIdItem) {
    if (this.associateId == null) {
      this.associateId = new ArrayList<AssociateId>();
    }
    this.associateId.add(associateIdItem);
    return this;
  }

   /**
   * 0 to N identifiers to associate the event for a specific UE or flow.
   * @return associateId
  **/
  @Schema(description = "0 to N identifiers to associate the event for a specific UE or flow.")
  public List<AssociateId> getAssociateId() {
    return associateId;
  }

  public void setAssociateId(List<AssociateId> associateId) {
    this.associateId = associateId;
  }

  public RabInfoUeInfo erabInfo(List<RabInfoErabInfo> erabInfo) {
    this.erabInfo = erabInfo;
    return this;
  }

  public RabInfoUeInfo addErabInfoItem(RabInfoErabInfo erabInfoItem) {
    if (this.erabInfo == null) {
      this.erabInfo = new ArrayList<RabInfoErabInfo>();
    }
    this.erabInfo.add(erabInfoItem);
    return this;
  }

   /**
   * Information on E-RAB as defined below.
   * @return erabInfo
  **/
  @Schema(description = "Information on E-RAB as defined below.")
  public List<RabInfoErabInfo> getErabInfo() {
    return erabInfo;
  }

  public void setErabInfo(List<RabInfoErabInfo> erabInfo) {
    this.erabInfo = erabInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RabInfoUeInfo rabInfoUeInfo = (RabInfoUeInfo) o;
    return Objects.equals(this.associateId, rabInfoUeInfo.associateId) &&
        Objects.equals(this.erabInfo, rabInfoUeInfo.erabInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associateId, erabInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RabInfoUeInfo {\n");
    
    sb.append("    associateId: ").append(toIndentedString(associateId)).append("\n");
    sb.append("    erabInfo: ").append(toIndentedString(erabInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
