/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * RabInfoErabInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class RabInfoErabInfo {
  @SerializedName("erabId")
  private Integer erabId = null;

  @SerializedName("erabQosParameters")
  private RabEstNotificationErabQosParameters erabQosParameters = null;

  public RabInfoErabInfo erabId(Integer erabId) {
    this.erabId = erabId;
    return this;
  }

   /**
   * The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].
   * @return erabId
  **/
  @Schema(description = "The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].")
  public Integer getErabId() {
    return erabId;
  }

  public void setErabId(Integer erabId) {
    this.erabId = erabId;
  }

  public RabInfoErabInfo erabQosParameters(RabEstNotificationErabQosParameters erabQosParameters) {
    this.erabQosParameters = erabQosParameters;
    return this;
  }

   /**
   * Get erabQosParameters
   * @return erabQosParameters
  **/
  @Schema(description = "")
  public RabEstNotificationErabQosParameters getErabQosParameters() {
    return erabQosParameters;
  }

  public void setErabQosParameters(RabEstNotificationErabQosParameters erabQosParameters) {
    this.erabQosParameters = erabQosParameters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RabInfoErabInfo rabInfoErabInfo = (RabInfoErabInfo) o;
    return Objects.equals(this.erabId, rabInfoErabInfo.erabId) &&
        Objects.equals(this.erabQosParameters, rabInfoErabInfo.erabQosParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(erabId, erabQosParameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RabInfoErabInfo {\n");
    
    sb.append("    erabId: ").append(toIndentedString(erabId)).append("\n");
    sb.append("    erabQosParameters: ").append(toIndentedString(erabQosParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
