/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * RabInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class RabInfo {
  @SerializedName("appInstanceId")
  private String appInstanceId = null;

  @SerializedName("cellUserInfo")
  private List<RabInfoCellUserInfo> cellUserInfo = null;

  @SerializedName("requestId")
  private String requestId = null;

  @SerializedName("timeStamp")
  private TimeStamp timeStamp = null;

  public RabInfo appInstanceId(String appInstanceId) {
    this.appInstanceId = appInstanceId;
    return this;
  }

   /**
   * Unique identifier for the MEC application instance.
   * @return appInstanceId
  **/
  @Schema(required = true, description = "Unique identifier for the MEC application instance.")
  public String getAppInstanceId() {
    return appInstanceId;
  }

  public void setAppInstanceId(String appInstanceId) {
    this.appInstanceId = appInstanceId;
  }

  public RabInfo cellUserInfo(List<RabInfoCellUserInfo> cellUserInfo) {
    this.cellUserInfo = cellUserInfo;
    return this;
  }

  public RabInfo addCellUserInfoItem(RabInfoCellUserInfo cellUserInfoItem) {
    if (this.cellUserInfo == null) {
      this.cellUserInfo = new ArrayList<RabInfoCellUserInfo>();
    }
    this.cellUserInfo.add(cellUserInfoItem);
    return this;
  }

   /**
   * The information on users per cell as defined below.
   * @return cellUserInfo
  **/
  @Schema(description = "The information on users per cell as defined below.")
  public List<RabInfoCellUserInfo> getCellUserInfo() {
    return cellUserInfo;
  }

  public void setCellUserInfo(List<RabInfoCellUserInfo> cellUserInfo) {
    this.cellUserInfo = cellUserInfo;
  }

  public RabInfo requestId(String requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Unique identifier allocated by the service consumer for the RAB Information request.
   * @return requestId
  **/
  @Schema(required = true, description = "Unique identifier allocated by the service consumer for the RAB Information request.")
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }

  public RabInfo timeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @Schema(description = "")
  public TimeStamp getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RabInfo rabInfo = (RabInfo) o;
    return Objects.equals(this.appInstanceId, rabInfo.appInstanceId) &&
        Objects.equals(this.cellUserInfo, rabInfo.cellUserInfo) &&
        Objects.equals(this.requestId, rabInfo.requestId) &&
        Objects.equals(this.timeStamp, rabInfo.timeStamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appInstanceId, cellUserInfo, requestId, timeStamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RabInfo {\n");
    
    sb.append("    appInstanceId: ").append(toIndentedString(appInstanceId)).append("\n");
    sb.append("    cellUserInfo: ").append(toIndentedString(cellUserInfo)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
