/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * RabModNotification
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class RabModNotification implements OneOfInlineNotification {
  @SerializedName("associateId")
  private List<AssociateId> associateId = null;

  @SerializedName("ecgi")
  private Ecgi ecgi = null;

  @SerializedName("erabId")
  private Integer erabId = null;

  @SerializedName("erabQosParameters")
  private RabModNotificationErabQosParameters erabQosParameters = null;

  @SerializedName("notificationType")
  private String notificationType = null;

  @SerializedName("timeStamp")
  private TimeStamp timeStamp = null;

  public RabModNotification associateId(List<AssociateId> associateId) {
    this.associateId = associateId;
    return this;
  }

  public RabModNotification addAssociateIdItem(AssociateId associateIdItem) {
    if (this.associateId == null) {
      this.associateId = new ArrayList<AssociateId>();
    }
    this.associateId.add(associateIdItem);
    return this;
  }

   /**
   * 0 to N identifiers to bind the event for a specific UE or flow. 
   * @return associateId
  **/
  @Schema(description = "0 to N identifiers to bind the event for a specific UE or flow. ")
  public List<AssociateId> getAssociateId() {
    return associateId;
  }

  public void setAssociateId(List<AssociateId> associateId) {
    this.associateId = associateId;
  }

  public RabModNotification ecgi(Ecgi ecgi) {
    this.ecgi = ecgi;
    return this;
  }

   /**
   * Get ecgi
   * @return ecgi
  **/
  @Schema(required = true, description = "")
  public Ecgi getEcgi() {
    return ecgi;
  }

  public void setEcgi(Ecgi ecgi) {
    this.ecgi = ecgi;
  }

  public RabModNotification erabId(Integer erabId) {
    this.erabId = erabId;
    return this;
  }

   /**
   * The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].
   * @return erabId
  **/
  @Schema(required = true, description = "The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].")
  public Integer getErabId() {
    return erabId;
  }

  public void setErabId(Integer erabId) {
    this.erabId = erabId;
  }

  public RabModNotification erabQosParameters(RabModNotificationErabQosParameters erabQosParameters) {
    this.erabQosParameters = erabQosParameters;
    return this;
  }

   /**
   * Get erabQosParameters
   * @return erabQosParameters
  **/
  @Schema(description = "")
  public RabModNotificationErabQosParameters getErabQosParameters() {
    return erabQosParameters;
  }

  public void setErabQosParameters(RabModNotificationErabQosParameters erabQosParameters) {
    this.erabQosParameters = erabQosParameters;
  }

  public RabModNotification notificationType(String notificationType) {
    this.notificationType = notificationType;
    return this;
  }

   /**
   * Shall be set to \&quot;RabModNotification\&quot;.
   * @return notificationType
  **/
  @Schema(required = true, description = "Shall be set to \"RabModNotification\".")
  public String getNotificationType() {
    return notificationType;
  }

  public void setNotificationType(String notificationType) {
    this.notificationType = notificationType;
  }

  public RabModNotification timeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @Schema(description = "")
  public TimeStamp getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RabModNotification rabModNotification = (RabModNotification) o;
    return Objects.equals(this.associateId, rabModNotification.associateId) &&
        Objects.equals(this.ecgi, rabModNotification.ecgi) &&
        Objects.equals(this.erabId, rabModNotification.erabId) &&
        Objects.equals(this.erabQosParameters, rabModNotification.erabQosParameters) &&
        Objects.equals(this.notificationType, rabModNotification.notificationType) &&
        Objects.equals(this.timeStamp, rabModNotification.timeStamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associateId, ecgi, erabId, erabQosParameters, notificationType, timeStamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RabModNotification {\n");
    
    sb.append("    associateId: ").append(toIndentedString(associateId)).append("\n");
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    erabId: ").append(toIndentedString(erabId)).append("\n");
    sb.append("    erabQosParameters: ").append(toIndentedString(erabQosParameters)).append("\n");
    sb.append("    notificationType: ").append(toIndentedString(notificationType)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
