/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * The release information for the E-RAB as defined below.
 */
@Schema(description = "The release information for the E-RAB as defined below.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class RabRelNotificationErabReleaseInfo {
  @SerializedName("erabId")
  private Integer erabId = null;

  public RabRelNotificationErabReleaseInfo erabId(Integer erabId) {
    this.erabId = erabId;
    return this;
  }

   /**
   * The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].
   * @return erabId
  **/
  @Schema(required = true, description = "The attribute that uniquely identifies a Radio Access bearer for specific UE as defined in ETSI TS 136 413 [i.3].")
  public Integer getErabId() {
    return erabId;
  }

  public void setErabId(Integer erabId) {
    this.erabId = erabId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RabRelNotificationErabReleaseInfo rabRelNotificationErabReleaseInfo = (RabRelNotificationErabReleaseInfo) o;
    return Objects.equals(this.erabId, rabRelNotificationErabReleaseInfo.erabId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(erabId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RabRelNotificationErabReleaseInfo {\n");
    
    sb.append("    erabId: ").append(toIndentedString(erabId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
