/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * RabRelNotification
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class RabRelNotification implements OneOfInlineNotification {
  @SerializedName("associateId")
  private List<AssociateId> associateId = null;

  @SerializedName("ecgi")
  private Ecgi ecgi = null;

  @SerializedName("erabReleaseInfo")
  private RabRelNotificationErabReleaseInfo erabReleaseInfo = null;

  @SerializedName("notificationType")
  private String notificationType = null;

  @SerializedName("timeStamp")
  private TimeStamp timeStamp = null;

  public RabRelNotification associateId(List<AssociateId> associateId) {
    this.associateId = associateId;
    return this;
  }

  public RabRelNotification addAssociateIdItem(AssociateId associateIdItem) {
    if (this.associateId == null) {
      this.associateId = new ArrayList<AssociateId>();
    }
    this.associateId.add(associateIdItem);
    return this;
  }

   /**
   * 0 to N identifiers to bind the event for a specific UE or flow as defined below.
   * @return associateId
  **/
  @Schema(description = "0 to N identifiers to bind the event for a specific UE or flow as defined below.")
  public List<AssociateId> getAssociateId() {
    return associateId;
  }

  public void setAssociateId(List<AssociateId> associateId) {
    this.associateId = associateId;
  }

  public RabRelNotification ecgi(Ecgi ecgi) {
    this.ecgi = ecgi;
    return this;
  }

   /**
   * Get ecgi
   * @return ecgi
  **/
  @Schema(required = true, description = "")
  public Ecgi getEcgi() {
    return ecgi;
  }

  public void setEcgi(Ecgi ecgi) {
    this.ecgi = ecgi;
  }

  public RabRelNotification erabReleaseInfo(RabRelNotificationErabReleaseInfo erabReleaseInfo) {
    this.erabReleaseInfo = erabReleaseInfo;
    return this;
  }

   /**
   * Get erabReleaseInfo
   * @return erabReleaseInfo
  **/
  @Schema(required = true, description = "")
  public RabRelNotificationErabReleaseInfo getErabReleaseInfo() {
    return erabReleaseInfo;
  }

  public void setErabReleaseInfo(RabRelNotificationErabReleaseInfo erabReleaseInfo) {
    this.erabReleaseInfo = erabReleaseInfo;
  }

  public RabRelNotification notificationType(String notificationType) {
    this.notificationType = notificationType;
    return this;
  }

   /**
   * Shall be set to \&quot;RabRelNotification\&quot;.
   * @return notificationType
  **/
  @Schema(required = true, description = "Shall be set to \"RabRelNotification\".")
  public String getNotificationType() {
    return notificationType;
  }

  public void setNotificationType(String notificationType) {
    this.notificationType = notificationType;
  }

  public RabRelNotification timeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @Schema(description = "")
  public TimeStamp getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RabRelNotification rabRelNotification = (RabRelNotification) o;
    return Objects.equals(this.associateId, rabRelNotification.associateId) &&
        Objects.equals(this.ecgi, rabRelNotification.ecgi) &&
        Objects.equals(this.erabReleaseInfo, rabRelNotification.erabReleaseInfo) &&
        Objects.equals(this.notificationType, rabRelNotification.notificationType) &&
        Objects.equals(this.timeStamp, rabRelNotification.timeStamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associateId, ecgi, erabReleaseInfo, notificationType, timeStamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RabRelNotification {\n");
    
    sb.append("    associateId: ").append(toIndentedString(associateId)).append("\n");
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    erabReleaseInfo: ").append(toIndentedString(erabReleaseInfo)).append("\n");
    sb.append("    notificationType: ").append(toIndentedString(notificationType)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
