/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ResultsPerSsbIndexList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class ResultsPerSsbIndexList {
  @SerializedName("resultsPerSsbIndex")
  private List<ResultsPerSsbIndexListResultsPerSsbIndex> resultsPerSsbIndex = null;

  public ResultsPerSsbIndexList resultsPerSsbIndex(List<ResultsPerSsbIndexListResultsPerSsbIndex> resultsPerSsbIndex) {
    this.resultsPerSsbIndex = resultsPerSsbIndex;
    return this;
  }

  public ResultsPerSsbIndexList addResultsPerSsbIndexItem(ResultsPerSsbIndexListResultsPerSsbIndex resultsPerSsbIndexItem) {
    if (this.resultsPerSsbIndex == null) {
      this.resultsPerSsbIndex = new ArrayList<ResultsPerSsbIndexListResultsPerSsbIndex>();
    }
    this.resultsPerSsbIndex.add(resultsPerSsbIndexItem);
    return this;
  }

   /**
   * Get resultsPerSsbIndex
   * @return resultsPerSsbIndex
  **/
  @Schema(description = "")
  public List<ResultsPerSsbIndexListResultsPerSsbIndex> getResultsPerSsbIndex() {
    return resultsPerSsbIndex;
  }

  public void setResultsPerSsbIndex(List<ResultsPerSsbIndexListResultsPerSsbIndex> resultsPerSsbIndex) {
    this.resultsPerSsbIndex = resultsPerSsbIndex;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultsPerSsbIndexList resultsPerSsbIndexList = (ResultsPerSsbIndexList) o;
    return Objects.equals(this.resultsPerSsbIndex, resultsPerSsbIndexList.resultsPerSsbIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultsPerSsbIndex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultsPerSsbIndexList {\n");
    
    sb.append("    resultsPerSsbIndex: ").append(toIndentedString(resultsPerSsbIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
