/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * ResultsPerCsiRsIndex
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class ResultsPerCsiRsIndex {
  @SerializedName("csiRsIndex")
  private Integer csiRsIndex = null;

  @SerializedName("csiRsResults")
  private MeasQuantityResultsNr csiRsResults = null;

  public ResultsPerCsiRsIndex csiRsIndex(Integer csiRsIndex) {
    this.csiRsIndex = csiRsIndex;
    return this;
  }

   /**
   * Get csiRsIndex
   * @return csiRsIndex
  **/
  @Schema(required = true, description = "")
  public Integer getCsiRsIndex() {
    return csiRsIndex;
  }

  public void setCsiRsIndex(Integer csiRsIndex) {
    this.csiRsIndex = csiRsIndex;
  }

  public ResultsPerCsiRsIndex csiRsResults(MeasQuantityResultsNr csiRsResults) {
    this.csiRsResults = csiRsResults;
    return this;
  }

   /**
   * Get csiRsResults
   * @return csiRsResults
  **/
  @Schema(description = "")
  public MeasQuantityResultsNr getCsiRsResults() {
    return csiRsResults;
  }

  public void setCsiRsResults(MeasQuantityResultsNr csiRsResults) {
    this.csiRsResults = csiRsResults;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultsPerCsiRsIndex resultsPerCsiRsIndex = (ResultsPerCsiRsIndex) o;
    return Objects.equals(this.csiRsIndex, resultsPerCsiRsIndex.csiRsIndex) &&
        Objects.equals(this.csiRsResults, resultsPerCsiRsIndex.csiRsResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(csiRsIndex, csiRsResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultsPerCsiRsIndex {\n");
    
    sb.append("    csiRsIndex: ").append(toIndentedString(csiRsIndex)).append("\n");
    sb.append("    csiRsResults: ").append(toIndentedString(csiRsResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
