/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ResultsPerCsiRsIndexList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class ResultsPerCsiRsIndexList {
  @SerializedName("resultsPerCsiRsIndex")
  private List<ResultsPerCsiRsIndexListResultsPerCsiRsIndex> resultsPerCsiRsIndex = null;

  public ResultsPerCsiRsIndexList resultsPerCsiRsIndex(List<ResultsPerCsiRsIndexListResultsPerCsiRsIndex> resultsPerCsiRsIndex) {
    this.resultsPerCsiRsIndex = resultsPerCsiRsIndex;
    return this;
  }

  public ResultsPerCsiRsIndexList addResultsPerCsiRsIndexItem(ResultsPerCsiRsIndexListResultsPerCsiRsIndex resultsPerCsiRsIndexItem) {
    if (this.resultsPerCsiRsIndex == null) {
      this.resultsPerCsiRsIndex = new ArrayList<ResultsPerCsiRsIndexListResultsPerCsiRsIndex>();
    }
    this.resultsPerCsiRsIndex.add(resultsPerCsiRsIndexItem);
    return this;
  }

   /**
   * Get resultsPerCsiRsIndex
   * @return resultsPerCsiRsIndex
  **/
  @Schema(description = "")
  public List<ResultsPerCsiRsIndexListResultsPerCsiRsIndex> getResultsPerCsiRsIndex() {
    return resultsPerCsiRsIndex;
  }

  public void setResultsPerCsiRsIndex(List<ResultsPerCsiRsIndexListResultsPerCsiRsIndex> resultsPerCsiRsIndex) {
    this.resultsPerCsiRsIndex = resultsPerCsiRsIndex;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultsPerCsiRsIndexList resultsPerCsiRsIndexList = (ResultsPerCsiRsIndexList) o;
    return Objects.equals(this.resultsPerCsiRsIndex, resultsPerCsiRsIndexList.resultsPerCsiRsIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultsPerCsiRsIndex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultsPerCsiRsIndexList {\n");
    
    sb.append("    resultsPerCsiRsIndex: ").append(toIndentedString(resultsPerCsiRsIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
