/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * ResultsPerSsbIndex
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class ResultsPerSsbIndex {
  @SerializedName("ssbIndex")
  private Integer ssbIndex = null;

  @SerializedName("ssbResults")
  private MeasQuantityResultsNr ssbResults = null;

  public ResultsPerSsbIndex ssbIndex(Integer ssbIndex) {
    this.ssbIndex = ssbIndex;
    return this;
  }

   /**
   * Get ssbIndex
   * @return ssbIndex
  **/
  @Schema(required = true, description = "")
  public Integer getSsbIndex() {
    return ssbIndex;
  }

  public void setSsbIndex(Integer ssbIndex) {
    this.ssbIndex = ssbIndex;
  }

  public ResultsPerSsbIndex ssbResults(MeasQuantityResultsNr ssbResults) {
    this.ssbResults = ssbResults;
    return this;
  }

   /**
   * Get ssbResults
   * @return ssbResults
  **/
  @Schema(description = "")
  public MeasQuantityResultsNr getSsbResults() {
    return ssbResults;
  }

  public void setSsbResults(MeasQuantityResultsNr ssbResults) {
    this.ssbResults = ssbResults;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultsPerSsbIndex resultsPerSsbIndex = (ResultsPerSsbIndex) o;
    return Objects.equals(this.ssbIndex, resultsPerSsbIndex.ssbIndex) &&
        Objects.equals(this.ssbResults, resultsPerSsbIndex.ssbResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ssbIndex, ssbResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultsPerSsbIndex {\n");
    
    sb.append("    ssbIndex: ").append(toIndentedString(ssbIndex)).append("\n");
    sb.append("    ssbResults: ").append(toIndentedString(ssbResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
