/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * RsIndexResults
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class RsIndexResults {
  @SerializedName("resultsCsiRsIndexes")
  private ResultsPerCsiRsIndexList resultsCsiRsIndexes = null;

  @SerializedName("resultsSsbIndexes")
  private ResultsPerSsbIndexList resultsSsbIndexes = null;

  public RsIndexResults resultsCsiRsIndexes(ResultsPerCsiRsIndexList resultsCsiRsIndexes) {
    this.resultsCsiRsIndexes = resultsCsiRsIndexes;
    return this;
  }

   /**
   * Get resultsCsiRsIndexes
   * @return resultsCsiRsIndexes
  **/
  @Schema(required = true, description = "")
  public ResultsPerCsiRsIndexList getResultsCsiRsIndexes() {
    return resultsCsiRsIndexes;
  }

  public void setResultsCsiRsIndexes(ResultsPerCsiRsIndexList resultsCsiRsIndexes) {
    this.resultsCsiRsIndexes = resultsCsiRsIndexes;
  }

  public RsIndexResults resultsSsbIndexes(ResultsPerSsbIndexList resultsSsbIndexes) {
    this.resultsSsbIndexes = resultsSsbIndexes;
    return this;
  }

   /**
   * Get resultsSsbIndexes
   * @return resultsSsbIndexes
  **/
  @Schema(required = true, description = "")
  public ResultsPerSsbIndexList getResultsSsbIndexes() {
    return resultsSsbIndexes;
  }

  public void setResultsSsbIndexes(ResultsPerSsbIndexList resultsSsbIndexes) {
    this.resultsSsbIndexes = resultsSsbIndexes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RsIndexResults rsIndexResults = (RsIndexResults) o;
    return Objects.equals(this.resultsCsiRsIndexes, rsIndexResults.resultsCsiRsIndexes) &&
        Objects.equals(this.resultsSsbIndexes, rsIndexResults.resultsSsbIndexes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultsCsiRsIndexes, resultsSsbIndexes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RsIndexResults {\n");
    
    sb.append("    resultsCsiRsIndexes: ").append(toIndentedString(resultsCsiRsIndexes)).append("\n");
    sb.append("    resultsSsbIndexes: ").append(toIndentedString(resultsSsbIndexes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
