/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * As defined below.
 */
@Schema(description = "As defined below.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class S1BearerSubscriptionS1BearerSubscriptionCriteria {
  @SerializedName("associateId")
  private List<AssociateId> associateId = null;

  @SerializedName("ecgi")
  private List<Ecgi> ecgi = null;

  @SerializedName("erabId")
  private List<Integer> erabId = null;

  public S1BearerSubscriptionS1BearerSubscriptionCriteria associateId(List<AssociateId> associateId) {
    this.associateId = associateId;
    return this;
  }

  public S1BearerSubscriptionS1BearerSubscriptionCriteria addAssociateIdItem(AssociateId associateIdItem) {
    if (this.associateId == null) {
      this.associateId = new ArrayList<AssociateId>();
    }
    this.associateId.add(associateIdItem);
    return this;
  }

   /**
   * 0 to N identifiers to associate the events for a specific UE or a flow.
   * @return associateId
  **/
  @Schema(description = "0 to N identifiers to associate the events for a specific UE or a flow.")
  public List<AssociateId> getAssociateId() {
    return associateId;
  }

  public void setAssociateId(List<AssociateId> associateId) {
    this.associateId = associateId;
  }

  public S1BearerSubscriptionS1BearerSubscriptionCriteria ecgi(List<Ecgi> ecgi) {
    this.ecgi = ecgi;
    return this;
  }

  public S1BearerSubscriptionS1BearerSubscriptionCriteria addEcgiItem(Ecgi ecgiItem) {
    if (this.ecgi == null) {
      this.ecgi = new ArrayList<Ecgi>();
    }
    this.ecgi.add(ecgiItem);
    return this;
  }

   /**
   * E-UTRAN Cell Global Identifier.
   * @return ecgi
  **/
  @Schema(description = "E-UTRAN Cell Global Identifier.")
  public List<Ecgi> getEcgi() {
    return ecgi;
  }

  public void setEcgi(List<Ecgi> ecgi) {
    this.ecgi = ecgi;
  }

  public S1BearerSubscriptionS1BearerSubscriptionCriteria erabId(List<Integer> erabId) {
    this.erabId = erabId;
    return this;
  }

  public S1BearerSubscriptionS1BearerSubscriptionCriteria addErabIdItem(Integer erabIdItem) {
    if (this.erabId == null) {
      this.erabId = new ArrayList<Integer>();
    }
    this.erabId.add(erabIdItem);
    return this;
  }

   /**
   * The attribute that uniquely identifies a S1 bearer for a specific UE, as defined in ETSI TS 136 413 [i.3].
   * @return erabId
  **/
  @Schema(description = "The attribute that uniquely identifies a S1 bearer for a specific UE, as defined in ETSI TS 136 413 [i.3].")
  public List<Integer> getErabId() {
    return erabId;
  }

  public void setErabId(List<Integer> erabId) {
    this.erabId = erabId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S1BearerSubscriptionS1BearerSubscriptionCriteria s1BearerSubscriptionS1BearerSubscriptionCriteria = (S1BearerSubscriptionS1BearerSubscriptionCriteria) o;
    return Objects.equals(this.associateId, s1BearerSubscriptionS1BearerSubscriptionCriteria.associateId) &&
        Objects.equals(this.ecgi, s1BearerSubscriptionS1BearerSubscriptionCriteria.ecgi) &&
        Objects.equals(this.erabId, s1BearerSubscriptionS1BearerSubscriptionCriteria.erabId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associateId, ecgi, erabId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S1BearerSubscriptionS1BearerSubscriptionCriteria {\n");
    
    sb.append("    associateId: ").append(toIndentedString(associateId)).append("\n");
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    erabId: ").append(toIndentedString(erabId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
