/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * S1BearerInfoS1BearerInfoDetailed
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class S1BearerInfoS1BearerInfoDetailed {
  @SerializedName("enbInfo")
  private S1BearerInfoEnbInfo enbInfo = null;

  @SerializedName("erabId")
  private Integer erabId = null;

  @SerializedName("sGwInfo")
  private S1BearerInfoSGwInfo sGwInfo = null;

  public S1BearerInfoS1BearerInfoDetailed enbInfo(S1BearerInfoEnbInfo enbInfo) {
    this.enbInfo = enbInfo;
    return this;
  }

   /**
   * Get enbInfo
   * @return enbInfo
  **/
  @Schema(description = "")
  public S1BearerInfoEnbInfo getEnbInfo() {
    return enbInfo;
  }

  public void setEnbInfo(S1BearerInfoEnbInfo enbInfo) {
    this.enbInfo = enbInfo;
  }

  public S1BearerInfoS1BearerInfoDetailed erabId(Integer erabId) {
    this.erabId = erabId;
    return this;
  }

   /**
   * The attribute that uniquely identifies a S1 bearer for a specific UE, as defined in ETSI TS 136 413 [i.3].
   * @return erabId
  **/
  @Schema(description = "The attribute that uniquely identifies a S1 bearer for a specific UE, as defined in ETSI TS 136 413 [i.3].")
  public Integer getErabId() {
    return erabId;
  }

  public void setErabId(Integer erabId) {
    this.erabId = erabId;
  }

  public S1BearerInfoS1BearerInfoDetailed sGwInfo(S1BearerInfoSGwInfo sGwInfo) {
    this.sGwInfo = sGwInfo;
    return this;
  }

   /**
   * Get sGwInfo
   * @return sGwInfo
  **/
  @Schema(description = "")
  public S1BearerInfoSGwInfo getSGwInfo() {
    return sGwInfo;
  }

  public void setSGwInfo(S1BearerInfoSGwInfo sGwInfo) {
    this.sGwInfo = sGwInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S1BearerInfoS1BearerInfoDetailed s1BearerInfoS1BearerInfoDetailed = (S1BearerInfoS1BearerInfoDetailed) o;
    return Objects.equals(this.enbInfo, s1BearerInfoS1BearerInfoDetailed.enbInfo) &&
        Objects.equals(this.erabId, s1BearerInfoS1BearerInfoDetailed.erabId) &&
        Objects.equals(this.sGwInfo, s1BearerInfoS1BearerInfoDetailed.sGwInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enbInfo, erabId, sGwInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S1BearerInfoS1BearerInfoDetailed {\n");
    
    sb.append("    enbInfo: ").append(toIndentedString(enbInfo)).append("\n");
    sb.append("    erabId: ").append(toIndentedString(erabId)).append("\n");
    sb.append("    sGwInfo: ").append(toIndentedString(sGwInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
