/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Information on specific UE that matches the criteria in S1BearerSubscription as defined below.
 */
@Schema(description = "Information on specific UE that matches the criteria in S1BearerSubscription as defined below.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class S1BearerNotificationS1UeInfo {
  @SerializedName("associateId")
  private List<AssociateId> associateId = null;

  @SerializedName("ecgi")
  private List<Ecgi> ecgi = new ArrayList<Ecgi>();

  @SerializedName("s1BearerInfo")
  private List<S1BearerInfoS1BearerInfoDetailed> s1BearerInfo = new ArrayList<S1BearerInfoS1BearerInfoDetailed>();

  @SerializedName("tempUeId")
  private CellChangeNotificationTempUeId tempUeId = null;

  public S1BearerNotificationS1UeInfo associateId(List<AssociateId> associateId) {
    this.associateId = associateId;
    return this;
  }

  public S1BearerNotificationS1UeInfo addAssociateIdItem(AssociateId associateIdItem) {
    if (this.associateId == null) {
      this.associateId = new ArrayList<AssociateId>();
    }
    this.associateId.add(associateIdItem);
    return this;
  }

   /**
   * 0 to N identifiers to associate the information for a specific UE or flow.
   * @return associateId
  **/
  @Schema(description = "0 to N identifiers to associate the information for a specific UE or flow.")
  public List<AssociateId> getAssociateId() {
    return associateId;
  }

  public void setAssociateId(List<AssociateId> associateId) {
    this.associateId = associateId;
  }

  public S1BearerNotificationS1UeInfo ecgi(List<Ecgi> ecgi) {
    this.ecgi = ecgi;
    return this;
  }

  public S1BearerNotificationS1UeInfo addEcgiItem(Ecgi ecgiItem) {
    this.ecgi.add(ecgiItem);
    return this;
  }

   /**
   * E-UTRAN Cell Global Identifier.
   * @return ecgi
  **/
  @Schema(required = true, description = "E-UTRAN Cell Global Identifier.")
  public List<Ecgi> getEcgi() {
    return ecgi;
  }

  public void setEcgi(List<Ecgi> ecgi) {
    this.ecgi = ecgi;
  }

  public S1BearerNotificationS1UeInfo s1BearerInfo(List<S1BearerInfoS1BearerInfoDetailed> s1BearerInfo) {
    this.s1BearerInfo = s1BearerInfo;
    return this;
  }

  public S1BearerNotificationS1UeInfo addS1BearerInfoItem(S1BearerInfoS1BearerInfoDetailed s1BearerInfoItem) {
    this.s1BearerInfo.add(s1BearerInfoItem);
    return this;
  }

   /**
   * S1 bearer information as defined below.
   * @return s1BearerInfo
  **/
  @Schema(required = true, description = "S1 bearer information as defined below.")
  public List<S1BearerInfoS1BearerInfoDetailed> getS1BearerInfo() {
    return s1BearerInfo;
  }

  public void setS1BearerInfo(List<S1BearerInfoS1BearerInfoDetailed> s1BearerInfo) {
    this.s1BearerInfo = s1BearerInfo;
  }

  public S1BearerNotificationS1UeInfo tempUeId(CellChangeNotificationTempUeId tempUeId) {
    this.tempUeId = tempUeId;
    return this;
  }

   /**
   * Get tempUeId
   * @return tempUeId
  **/
  @Schema(description = "")
  public CellChangeNotificationTempUeId getTempUeId() {
    return tempUeId;
  }

  public void setTempUeId(CellChangeNotificationTempUeId tempUeId) {
    this.tempUeId = tempUeId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S1BearerNotificationS1UeInfo s1BearerNotificationS1UeInfo = (S1BearerNotificationS1UeInfo) o;
    return Objects.equals(this.associateId, s1BearerNotificationS1UeInfo.associateId) &&
        Objects.equals(this.ecgi, s1BearerNotificationS1UeInfo.ecgi) &&
        Objects.equals(this.s1BearerInfo, s1BearerNotificationS1UeInfo.s1BearerInfo) &&
        Objects.equals(this.tempUeId, s1BearerNotificationS1UeInfo.tempUeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associateId, ecgi, s1BearerInfo, tempUeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S1BearerNotificationS1UeInfo {\n");
    
    sb.append("    associateId: ").append(toIndentedString(associateId)).append("\n");
    sb.append("    ecgi: ").append(toIndentedString(ecgi)).append("\n");
    sb.append("    s1BearerInfo: ").append(toIndentedString(s1BearerInfo)).append("\n");
    sb.append("    tempUeId: ").append(toIndentedString(tempUeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
