/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * S1BearerInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class S1BearerInfo {
  @SerializedName("s1UeInfo")
  private List<S1BearerInfoS1UeInfo> s1UeInfo = new ArrayList<S1BearerInfoS1UeInfo>();

  @SerializedName("timeStamp")
  private TimeStamp timeStamp = null;

  public S1BearerInfo s1UeInfo(List<S1BearerInfoS1UeInfo> s1UeInfo) {
    this.s1UeInfo = s1UeInfo;
    return this;
  }

  public S1BearerInfo addS1UeInfoItem(S1BearerInfoS1UeInfo s1UeInfoItem) {
    this.s1UeInfo.add(s1UeInfoItem);
    return this;
  }

   /**
   * Information on a specific UE as defined below.
   * @return s1UeInfo
  **/
  @Schema(required = true, description = "Information on a specific UE as defined below.")
  public List<S1BearerInfoS1UeInfo> getS1UeInfo() {
    return s1UeInfo;
  }

  public void setS1UeInfo(List<S1BearerInfoS1UeInfo> s1UeInfo) {
    this.s1UeInfo = s1UeInfo;
  }

  public S1BearerInfo timeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

   /**
   * Get timeStamp
   * @return timeStamp
  **/
  @Schema(description = "")
  public TimeStamp getTimeStamp() {
    return timeStamp;
  }

  public void setTimeStamp(TimeStamp timeStamp) {
    this.timeStamp = timeStamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S1BearerInfo s1BearerInfo = (S1BearerInfo) o;
    return Objects.equals(this.s1UeInfo, s1BearerInfo.s1UeInfo) &&
        Objects.equals(this.timeStamp, s1BearerInfo.timeStamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(s1UeInfo, timeStamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S1BearerInfo {\n");
    
    sb.append("    s1UeInfo: ").append(toIndentedString(s1UeInfo)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
