/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * S1 bearer information on GW side as defined below.
 */
@Schema(description = "S1 bearer information on GW side as defined below.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class S1BearerInfoSGwInfo {
  @SerializedName("ipAddress")
  private String ipAddress = null;

  @SerializedName("tunnelId")
  private String tunnelId = null;

  public S1BearerInfoSGwInfo ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * SGW transport layer address of this S1 bearer.
   * @return ipAddress
  **/
  @Schema(required = true, description = "SGW transport layer address of this S1 bearer.")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public S1BearerInfoSGwInfo tunnelId(String tunnelId) {
    this.tunnelId = tunnelId;
    return this;
  }

   /**
   * SGW GTP-U TEID of this S1 bearer.
   * @return tunnelId
  **/
  @Schema(required = true, description = "SGW GTP-U TEID of this S1 bearer.")
  public String getTunnelId() {
    return tunnelId;
  }

  public void setTunnelId(String tunnelId) {
    this.tunnelId = tunnelId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S1BearerInfoSGwInfo s1BearerInfoSGwInfo = (S1BearerInfoSGwInfo) o;
    return Objects.equals(this.ipAddress, s1BearerInfoSGwInfo.ipAddress) &&
        Objects.equals(this.tunnelId, s1BearerInfoSGwInfo.tunnelId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ipAddress, tunnelId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S1BearerInfoSGwInfo {\n");
    
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    tunnelId: ").append(toIndentedString(tunnelId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
