/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * SubscriptionLinkListLinksSubscription
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class SubscriptionLinkListLinksSubscription {
  @SerializedName("href")
  private String href = null;

  @SerializedName("subscriptionType")
  private String subscriptionType = null;

  public SubscriptionLinkListLinksSubscription href(String href) {
    this.href = href;
    return this;
  }

   /**
   * The URI referring to the subscription.
   * @return href
  **/
  @Schema(description = "The URI referring to the subscription.")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public SubscriptionLinkListLinksSubscription subscriptionType(String subscriptionType) {
    this.subscriptionType = subscriptionType;
    return this;
  }

   /**
   * Type of the subscription. The string shall be set according to the \&quot;subscriptionType\&quot; attribute of the associated subscription data type event defined in clause 6.3.
   * @return subscriptionType
  **/
  @Schema(description = "Type of the subscription. The string shall be set according to the \"subscriptionType\" attribute of the associated subscription data type event defined in clause 6.3.")
  public String getSubscriptionType() {
    return subscriptionType;
  }

  public void setSubscriptionType(String subscriptionType) {
    this.subscriptionType = subscriptionType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionLinkListLinksSubscription subscriptionLinkListLinksSubscription = (SubscriptionLinkListLinksSubscription) o;
    return Objects.equals(this.href, subscriptionLinkListLinksSubscription.href) &&
        Objects.equals(this.subscriptionType, subscriptionLinkListLinksSubscription.subscriptionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, subscriptionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionLinkListLinksSubscription {\n");
    
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    subscriptionType: ").append(toIndentedString(subscriptionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
