/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * List of hyperlinks related to the resource.
 */
@Schema(description = "List of hyperlinks related to the resource.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-09T15:33:56.133+01:00[Europe/Rome]")
public class SubscriptionLinkListLinks {
  @SerializedName("self")
  private LinkType self = null;

  @SerializedName("subscription")
  private List<SubscriptionLinkListLinksSubscription> subscription = null;

  public SubscriptionLinkListLinks self(LinkType self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @Schema(required = true, description = "")
  public LinkType getSelf() {
    return self;
  }

  public void setSelf(LinkType self) {
    this.self = self;
  }

  public SubscriptionLinkListLinks subscription(List<SubscriptionLinkListLinksSubscription> subscription) {
    this.subscription = subscription;
    return this;
  }

  public SubscriptionLinkListLinks addSubscriptionItem(SubscriptionLinkListLinksSubscription subscriptionItem) {
    if (this.subscription == null) {
      this.subscription = new ArrayList<SubscriptionLinkListLinksSubscription>();
    }
    this.subscription.add(subscriptionItem);
    return this;
  }

   /**
   * A link to a subscription.
   * @return subscription
  **/
  @Schema(description = "A link to a subscription.")
  public List<SubscriptionLinkListLinksSubscription> getSubscription() {
    return subscription;
  }

  public void setSubscription(List<SubscriptionLinkListLinksSubscription> subscription) {
    this.subscription = subscription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionLinkListLinks subscriptionLinkListLinks = (SubscriptionLinkListLinks) o;
    return Objects.equals(this.self, subscriptionLinkListLinks.self) &&
        Objects.equals(this.subscription, subscriptionLinkListLinks.subscription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, subscription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionLinkListLinks {\n");
    
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
