/*
 * ETSI GS MEC 012 - Radio Network Information API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI.
 *
 * OpenAPI spec version: 2.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * The enumeration Trigger represents specified triggers for a 5G UE Measurement Report. Full details can be found in ETSI TS 138 331 [i.13]). &lt;p&gt;0 &#x3D; NOT_AVAILABLE &lt;p&gt;1 &#x3D; NR_PERIODICAL &lt;p&gt;2 &#x3D; NR_CGI &lt;p&gt;10 &#x3D; EVENT_A1 &lt;p&gt;11 &#x3D; EVENT_A2 &lt;p&gt;12 &#x3D; EVENT_A3 &lt;p&gt;13 &#x3D; EVENT_A4 &lt;p&gt;14 &#x3D; EVENT_A5 &lt;p&gt;15 &#x3D; EVENT_A6 &lt;p&gt;20 &#x3D; INTER_RAT_PERIODICAL &lt;p&gt;21 &#x3D; INTER_RAT_CGI &lt;p&gt;30 &#x3D; EVENT_B1 &lt;p&gt;31 &#x3D; EVENT_B2
 */
@JsonAdapter(TriggerNr.Adapter.class)
public enum TriggerNr {
  NUMBER_0(0),
  NUMBER_1(1),
  NUMBER_2(2),
  NUMBER_10(10),
  NUMBER_11(11),
  NUMBER_12(12),
  NUMBER_13(13),
  NUMBER_14(14),
  NUMBER_15(15),
  NUMBER_20(20),
  NUMBER_21(21),
  NUMBER_30(30),
  NUMBER_31(31);

  private Integer value;

  TriggerNr(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TriggerNr fromValue(String text) {
    for (TriggerNr b : TriggerNr.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TriggerNr> {
    @Override
    public void write(final JsonWriter jsonWriter, final TriggerNr enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TriggerNr read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return TriggerNr.fromValue(String.valueOf(value));
    }
  }
}
